CREATE TABLE `bussiness_public_employee_department_ods_h` (
  `dept_id` bigint(20) NULL COMMENT "部门id",
  `employee_id` bigint(20) NULL COMMENT "工号",
  `is_delete` int(11) NULL COMMENT "是否删除",
  `id` varchar(16) NULL COMMENT "主键id" COLLATE UTF8MB4_GENERAL_CI,
  `date` datetime NULL COMMENT "分区",
  `name` varchar(32) NULL COMMENT "邮箱前缀" COLLATE UTF8MB4_GENERAL_CI,
  `timeline_id` bigint(20) NULL COMMENT "时间线ID",
  `dept_full_path` varchar(64) NULL COMMENT "部门路径" COLLATE UTF8MB4_GENERAL_CI,
  `dept_full_name` varchar(128) NULL COMMENT "部门全名：产品研发和工程架构部-Client Infrastructure-APM" COLLATE UTF8MB4_GENERAL_CI,
  `join_dept_time` datetime NULL COMMENT "加入部门时间",
  `leave_dept_time` datetime NULL COMMENT "离开部门时间",
  `is_current` int(11) NULL COMMENT "是否当前部门",
  `is_terminated` int(11) NULL COMMENT "是否离职",
  `creator` varchar(32) NULL COMMENT "创建人" COLLATE UTF8MB4_GENERAL_CI,
  `updater` varchar(32) NULL COMMENT "更新人" COLLATE UTF8MB4_GENERAL_CI,
  `create_time` datetime NULL COMMENT "创建时间",
  `update_time` datetime NULL COMMENT "更新时间",
  `api_valid_time` datetime NULL DEFAULT NULL COMMENT "API生效时间：替换join_dept_time",
  `api_invalid_time` datetime NULL DEFAULT NULL COMMENT "API失效时间：替换leave_dept_time"
);

CREATE TABLE `bussiness_public_employee_leader_ods_h` (
  `pid` int(11) NULL COMMENT "父节点id",
  `employee_id` bigint(20) NULL COMMENT "工号",
  `is_delete` int(11) NULL COMMENT "是否删除",
  `id` bigint(20) NULL COMMENT "主键id",
  `date` datetime NULL COMMENT "分区",
  `name` varchar(32) NULL COMMENT "人名" COLLATE UTF8MB4_GENERAL_CI,
  `timeline_id` bigint(20) NULL COMMENT "时间线ID",
  `report_full_path` varchar(256) NULL COMMENT "路径" COLLATE UTF8MB4_GENERAL_CI,
  `leader_id` bigint(20) NULL COMMENT "Leader ID",
  `start_report_time` datetime NULL COMMENT "加入团队时间",
  `end_report_time` datetime NULL COMMENT "离开团队时间",
  `is_terminated` int(11) NULL COMMENT "是否离职",
  `is_current` int(11) NULL COMMENT "是否当前汇报关系",
  `is_leaf` int(11) NULL COMMENT "是否底层雇员",
  `creator` varchar(32) NULL COMMENT "创建人" COLLATE UTF8MB4_GENERAL_CI,
  `updater` varchar(32) NULL COMMENT "更新人" COLLATE UTF8MB4_GENERAL_CI,
  `create_time` datetime NULL COMMENT "创建时间",
  `update_time` datetime NULL COMMENT "更新时间"
);

CREATE TABLE `bussiness_public_employee_ods_h` (
  `employee_id` bigint(20) NULL COMMENT "工号",
  `is_delete` int(11) NULL COMMENT "是否删除",
  `id` bigint(20) NULL COMMENT "主键id",
  `date` datetime NULL COMMENT "分区",
  `name` varchar(45) NULL COMMENT "邮箱前缀" COLLATE UTF8MB4_GENERAL_CI,
  `name_en` varchar(128) NULL COMMENT "英文名" COLLATE UTF8MB4_GENERAL_CI,
  `name_cn` varchar(128) NULL COMMENT "中文名" COLLATE UTF8MB4_GENERAL_CI,
  `email` varchar(255) NULL COMMENT "邮箱全称" COLLATE UTF8MB4_GENERAL_CI,
  `avatar` varchar(255) NULL COMMENT "头像地址" COLLATE UTF8MB4_GENERAL_CI,
  `employee_number` bigint(20) NULL COMMENT "工号",
  `employee_type` varchar(128) NULL COMMENT "员工类型，全职、实习等" COLLATE UTF8MB4_GENERAL_CI,
  `sequence` varchar(64) NULL COMMENT "序列" COLLATE UTF8MB4_GENERAL_CI,
  `city` varchar(64) NULL COMMENT "工作城市" COLLATE UTF8MB4_GENERAL_CI,
  `country` varchar(64) NULL COMMENT "工作国家" COLLATE UTF8MB4_GENERAL_CI,
  `join_time` datetime NULL COMMENT "入职时间",
  `entry_time` datetime NULL COMMENT "转正时间",
  `leave_time` datetime NULL COMMENT "离职时间",
  `is_terminated` int(11) NULL COMMENT "是否离职",
  `dept_full_name` varchar(256) NULL COMMENT "所在部门全名，当前所在部门" COLLATE UTF8MB4_GENERAL_CI,
  `creator` varchar(32) NULL COMMENT "创建人" COLLATE UTF8MB4_GENERAL_CI,
  `updater` varchar(32) NULL COMMENT "更新人" COLLATE UTF8MB4_GENERAL_CI,
  `create_time` datetime NULL COMMENT "创建时间",
  `update_time` datetime NULL COMMENT "更新时间",
  `job_category` varchar(128) NULL COMMENT "工作方向" COLLATE UTF8MB4_GENERAL_CI,
  `dept_id` bigint(20) NULL DEFAULT NULL COMMENT "部门ID",
  `is_need_code` int(11) NULL DEFAULT NULL COMMENT "是否需要编码人员，默认为0，不需要编码",
  `computer_get_time` datetime NULL DEFAULT NULL COMMENT "电脑领取时间：替换join_time",
  `computer_work_time` datetime NULL DEFAULT NULL COMMENT "电脑使用时间：替换entry_time",
  `computer_return_time` datetime NULL DEFAULT NULL COMMENT "电脑归还时间：替换leave_time"
);

CREATE TABLE `fatal_base_v2_dwd_h` (
  `fatal_create_time` datetime NULL COMMENT "事故创建时间",
  `fatal_fix_time` datetime NULL COMMENT "事故解决时间",
  `product_id` bigint(20) NULL COMMENT "产品线ID",
  `fatal_id` bigint(20) NULL COMMENT "事故id",
  `id` bigint(20) NULL COMMENT "自增ID",
  `date` datetime NULL COMMENT "分区",
  `is_delete` bigint(20) NULL COMMENT "是否删除",
  `fatal_start_time` datetime NULL COMMENT "事故开始时间",
  `fatal_aware_time` datetime NULL COMMENT "事故发现时间",
  `improvement_start_time` datetime NULL COMMENT "改进计划开始时间",
  `improvement_expect_end_time` datetime NULL COMMENT "改进计划预期结束时间",
  `improvement_act_end_time` datetime NULL COMMENT "改进计划实际结束时间",
  `response_time` datetime NULL COMMENT "响应时间：Oncall开始响应，开始处理事故的时间",
  `stoploss_end_time` datetime NULL COMMENT "止损操作完成的时间",
  `stoploss_start_time` datetime NULL COMMENT "止损开始：开始执行止损预案或其他恢复操作的时间",
  `email_sent_time` datetime NULL COMMENT "邮件发送时间",
  `update_time` datetime NULL COMMENT "更新时间",
  `dept_full_path` varchar(64) NULL COMMENT "部门id路径" COLLATE UTF8MB4_GENERAL_CI,
  `dept_full_name` varchar(256) NULL COMMENT "责任人所属部门" COLLATE UTF8MB4_GENERAL_CI,
  `fatal_name` varchar(200) NULL COMMENT "事故名称" COLLATE UTF8MB4_GENERAL_CI,
  `fatal_product` varchar(100) NULL COMMENT "所属产品模块" COLLATE UTF8MB4_GENERAL_CI,
  `fatal_product_child` varchar(64) NULL COMMENT "事故方子业务" COLLATE UTF8MB4_GENERAL_CI,
  `psm` varchar(64) NULL COMMENT "所属psm" COLLATE UTF8MB4_GENERAL_CI,
  `platform` varchar(64) NULL COMMENT "产生的平台：服务端、客户端、data、其他" COLLATE UTF8MB4_GENERAL_CI,
  `fatal_level` varchar(10) NULL COMMENT "等级" COLLATE UTF8MB4_GENERAL_CI,
  `sys_level` varchar(10) NULL COMMENT "系统等级" COLLATE UTF8MB4_GENERAL_CI,
  `modify_level` varchar(10) NULL COMMENT "用户修改等级" COLLATE UTF8MB4_GENERAL_CI,
  `source` varchar(64) NULL COMMENT "来源" COLLATE UTF8MB4_GENERAL_CI,
  `err_type` varchar(200) NULL COMMENT "错误分类" COLLATE UTF8MB4_GENERAL_CI,
  `err_sub_type` varchar(200) NULL COMMENT "错误子分类" COLLATE UTF8MB4_GENERAL_CI,
  `fatal_owner` varchar(64) NULL COMMENT "事故责任人" COLLATE UTF8MB4_GENERAL_CI,
  `affect_product` varchar(100) NULL COMMENT "影响产品" COLLATE UTF8MB4_GENERAL_CI,
  `affect_module` varchar(100) NULL COMMENT "影响模块" COLLATE UTF8MB4_GENERAL_CI,
  `affect_income` double NULL COMMENT "单个模块影响收入",
  `affect_income_total` double NULL COMMENT "整个事故影响收入",
  `affect_safe_types` varchar(100) NULL COMMENT "影响的安全等级类型列表" COLLATE UTF8MB4_GENERAL_CI,
  `improvement_content_key` varchar(100) NULL COMMENT "改进计划内容key" COLLATE UTF8MB4_GENERAL_CI,
  `improvement_status` varchar(200) NULL COMMENT "改进计划状态" COLLATE UTF8MB4_GENERAL_CI,
  `improvement_owners` varchar(200) NULL COMMENT "改进计划责任人" COLLATE UTF8MB4_GENERAL_CI,
  `improvement_owner_dept` varchar(256) NULL COMMENT "改进计划责任人所属部门" COLLATE UTF8MB4_GENERAL_CI,
  `improvement_level` varchar(10) NULL COMMENT "改进计划等级" COLLATE UTF8MB4_GENERAL_CI,
  `improvement_content` varchar(2000) NULL COMMENT "改进计划内容" COLLATE UTF8MB4_GENERAL_CI,
  `fatal_status` varchar(64) NULL COMMENT "事故状态，如事故创建、事故解决等" COLLATE UTF8MB4_GENERAL_CI,
  `creator` varchar(64) NULL COMMENT "事故创建者" COLLATE UTF8MB4_GENERAL_CI,
  `fatal_dept_full_name` varchar(100) NULL COMMENT "fatal上映射的所在部门全名，事故责任部门" COLLATE UTF8MB4_GENERAL_CI,
  `regulate_fatal_product` varchar(100) NULL COMMENT "用户校准字段：fatal_product" COLLATE UTF8MB4_GENERAL_CI,
  `level_modify_reason` varchar(2000) NULL COMMENT "等级修改原因" COLLATE UTF8MB4_GENERAL_CI,
  `fatal_score` double NULL COMMENT "事故分",
  `affect_tech_name` varchar(100) NULL COMMENT "单个模块影响的技术指标" COLLATE UTF8MB4_GENERAL_CI,
  `affect_user_active_ucnt` bigint(20) NULL COMMENT "单个模块用户影响的活跃用户数",
  `affect_user_affected_ucnt` bigint(20) NULL COMMENT "单个模块用户影响的影响用户数",
  `affect_availability_type` varchar(256) NULL COMMENT "影响：核心非核心功能类型" COLLATE UTF8MB4_GENERAL_CI,
  `env` varchar(32) NULL COMMENT "所属环境，线上、BOE" COLLATE UTF8MB4_GENERAL_CI,
  `root_causes_key` varchar(32) NULL COMMENT "根因分析：key" COLLATE UTF8MB4_GENERAL_CI,
  `root_causes_owners` varchar(32) NULL COMMENT "根因分析：责任人" COLLATE UTF8MB4_GENERAL_CI,
  `root_causes_role` varchar(32) NULL COMMENT "根因分析：角色" COLLATE UTF8MB4_GENERAL_CI,
  `root_causes_section` varchar(32) NULL COMMENT "根因分析：事故引入环节" COLLATE UTF8MB4_GENERAL_CI,
  `root_causes_cause_remark` varchar(5000) NULL COMMENT "根因分析：事故引入原因备注" COLLATE UTF8MB4_GENERAL_CI,
  `root_causes_case_type` varchar(64) NULL COMMENT "根因分析：事故引入原因类型" COLLATE UTF8MB4_GENERAL_CI,
  `risk_type` varchar(200) NULL COMMENT "引入风险类型" COLLATE UTF8MB4_GENERAL_CI,
  `project_type` varchar(100) NULL COMMENT "项目类型" COLLATE UTF8MB4_GENERAL_CI,
  `fatal_tags` varchar(512) NULL COMMENT "事故标签" COLLATE UTF8MB4_GENERAL_CI,
  `config_incident0_platform_name` varchar(100) NULL COMMENT "配置变更平台名称(配置变更数组第一个)" COLLATE UTF8MB4_GENERAL_CI,
  `config_incident0_url` varchar(500) NULL COMMENT "配置变更链接(配置变更数组第一个)" COLLATE UTF8MB4_GENERAL_CI,
  `code_review_url` varchar(500) NULL COMMENT "code diff 地址" COLLATE UTF8MB4_GENERAL_CI,
  `alarm_url` varchar(500) NULL COMMENT "报警地址" COLLATE UTF8MB4_GENERAL_CI,
  `feedback_url` varchar(500) NULL COMMENT "反馈地址" COLLATE UTF8MB4_GENERAL_CI,
  `is_secret` bigint(20) NULL COMMENT "是否保密",
  `is_private_product` bigint(20) NULL COMMENT "是否保密产品线",
  `fatal_update_time` datetime NULL COMMENT "fatal更新时间",
  `affect_currency` varchar(32) NULL COMMENT "收入影响货币单位 " COLLATE UTF8MB4_GENERAL_CI,
  `tce_url` varchar(500) NULL COMMENT "Tce上线单" COLLATE UTF8MB4_GENERAL_CI,
  `bits_url` varchar(500) NULL COMMENT "bits需求地址" COLLATE UTF8MB4_GENERAL_CI,
  `lark_doc_url` varchar(500) NULL COMMENT "线下复盘飞书文档地址" COLLATE UTF8MB4_GENERAL_CI,
  `redline_id` bigint(20) NULL COMMENT "红线id",
  `redline_owner` varchar(64) NULL COMMENT "红线责任人" COLLATE UTF8MB4_GENERAL_CI,
  `redline_name` varchar(200) NULL COMMENT "红线内容" COLLATE UTF8MB4_GENERAL_CI,
  `redline_score` double NULL COMMENT "红线扣分",
  `online_platform_type` varchar(64) NULL COMMENT "上线单类型" COLLATE UTF8MB4_GENERAL_CI,
  `devops_link` varchar(1000) NULL COMMENT "流水线链接" COLLATE UTF8MB4_GENERAL_CI,
  `review_create_time` datetime NULL COMMENT "事故最新Review时间",
  `client_side` bigint(20) NULL COMMENT "客户端类型",
  `client_effect` bigint(20) NULL COMMENT "客户端影响类型",
  `client_incident_phenomenon` varchar(256) NULL COMMENT "客户端事件现象" COLLATE UTF8MB4_GENERAL_CI,
  `feedback_count` bigint(20) NULL COMMENT "反馈数量",
  `fatal_review_time` datetime NULL COMMENT "复盘时间",
  `affect_final_level` varchar(64) NULL DEFAULT "" COMMENT "影响模块最终等级" COLLATE UTF8MB4_GENERAL_CI,
  `affect_depend_type` varchar(64) NULL DEFAULT "" COMMENT "影响模块依赖分类" COLLATE UTF8MB4_GENERAL_CI,
  `affect_depend_level` varchar(64) NULL DEFAULT "" COMMENT "影响模块依赖程度" COLLATE UTF8MB4_GENERAL_CI,
  `affect_start_time` datetime NULL COMMENT "影响模块开始时间",
  `affect_end_time` datetime NULL COMMENT "影响模块结束时间",
  `affect_disc_time` datetime NULL COMMENT "影响模块发现时间",
  `affect_response_time` datetime NULL COMMENT "影响模块响应时间",
  `affect_process_time` datetime NULL COMMENT "影响模块处理时间",
  `affect_recovery_time` datetime NULL COMMENT "影响模块恢复时间",
  `improvement_meego_url` varchar(1000) NULL COMMENT "改进计划关联的meego链接" COLLATE UTF8MB4_GENERAL_CI,
  `is_same_issue_occurred` bigint(20) NULL COMMENT "是否出现过相同的问题",
  `root_causes_improvement` varchar(1000) NULL COMMENT "根因分析：预防措施" COLLATE UTF8MB4_GENERAL_CI,
  `root_client` varchar(256) NULL COMMENT "根因客户端类型" COLLATE UTF8MB4_GENERAL_CI,
  `effect_client` varchar(256) NULL COMMENT "客户端影响类型" COLLATE UTF8MB4_GENERAL_CI,
  `custom_field_info` json NULL COMMENT "自定义字段信息",
  `region` varchar(32) NULL COMMENT "数据所属域" COLLATE UTF8MB4_GENERAL_CI,
  `improvement_acceptance_status` varchar(55) NULL COMMENT "改进计划验收状态" COLLATE UTF8MB4_GENERAL_CI,
  `improvement_expected_acceptance_time` varchar(55) NULL COMMENT "改进计划预计验收完成时间" COLLATE UTF8MB4_GENERAL_CI,
  `improvement_actual_acceptance_time` varchar(55) NULL COMMENT "改进计划实际验收完成时间" COLLATE UTF8MB4_GENERAL_CI,
  `level_custom_field_info` json NULL COMMENT "改进计划预计验收完成时间",
  `special_custom_field_info` json NULL COMMENT "改进计划实际验收完成时间",
  `affect_perception_channel` varchar(65533) NULL DEFAULT NULL COMMENT "受影响方发现渠道" COLLATE UTF8MB4_GENERAL_CI,
  `root_cause` varchar(65533) NULL DEFAULT NULL COMMENT "事故根因" COLLATE UTF8MB4_GENERAL_CI,
  `theoretical_loss` varchar(65533) NULL DEFAULT NULL COMMENT "理论资损额" COLLATE UTF8MB4_GENERAL_CI,
  `regular_meeting_name_list` json NULL DEFAULT NULL COMMENT "关联例会",
  `is_l0_scene` varchar(65533) NULL DEFAULT NULL COMMENT "是否是L0场景" COLLATE UTF8MB4_GENERAL_CI,
  `by_qa_test` varchar(65533) NULL DEFAULT NULL COMMENT "经QA测试" COLLATE UTF8MB4_GENERAL_CI,
  `affect_l0_scenes` varchar(65533) NULL DEFAULT NULL COMMENT "受影响L0核心场景" COLLATE UTF8MB4_GENERAL_CI,
  `affect_exchange_rate_to_cny` double NULL DEFAULT NULL COMMENT "汇率",
  `is_tracking_incident` varchar(65533) NULL DEFAULT NULL COMMENT "是否是埋点事故" COLLATE UTF8MB4_GENERAL_CI,
  `is_fatal_l0` varchar(65533) NULL DEFAULT NULL COMMENT "是否责任l0" COLLATE UTF8MB4_GENERAL_CI,
  `owner_create_report_full_path` varchar(65533) NULL DEFAULT NULL COMMENT "fatal owner创建时间汇报线路径" COLLATE UTF8MB4_GENERAL_CI,
  `redline_owner_create_report_full_path` varchar(65533) NULL DEFAULT NULL COMMENT "红线 owner创建时间汇报线路径" COLLATE UTF8MB4_GENERAL_CI,
  `owner_start_report_full_path` varchar(65533) NULL DEFAULT NULL COMMENT "fatal owner发现时间时间汇报线路径" COLLATE UTF8MB4_GENERAL_CI
);

CREATE TABLE `private_meego_auto_result_to_devmind` (
  `meego_id` varchar(128) NULL COMMENT "需求id" COLLATE UTF8MB4_GENERAL_CI,
  `date` datetime NULL COMMENT "分区",
  `simple_name` varchar(128) NULL COMMENT "需求空间名称" COLLATE UTF8MB4_GENERAL_CI,
  `business` varchar(128) NULL COMMENT "需求业务线" COLLATE UTF8MB4_GENERAL_CI,
  `meego_name` varchar(128) NULL COMMENT "需求名称" COLLATE UTF8MB4_GENERAL_CI,
  `meego_risk_level` varchar(128) NULL COMMENT "需求阶段回溯风险等级" COLLATE UTF8MB4_GENERAL_CI,
  `meego_risk_score` varchar(128) NULL COMMENT "需求阶段回溯风险分" COLLATE UTF8MB4_GENERAL_CI,
  `runtime_meego_risk_level` varchar(128) NULL COMMENT "需求阶段实时风险等级" COLLATE UTF8MB4_GENERAL_CI,
  `runtime_meego_risk_score` varchar(128) NULL COMMENT "需求阶段实时风险分" COLLATE UTF8MB4_GENERAL_CI,
  `test_in_risk_level` varchar(128) NULL COMMENT "提测阶段回溯风险等级" COLLATE UTF8MB4_GENERAL_CI,
  `test_in_risk_score` varchar(128) NULL COMMENT "提测阶段回溯风险分" COLLATE UTF8MB4_GENERAL_CI,
  `runtime_in_risk_level` varchar(128) NULL COMMENT "提测阶段实时风险等级" COLLATE UTF8MB4_GENERAL_CI,
  `runtime_in_risk_score` varchar(128) NULL COMMENT "提测阶段实时风险分" COLLATE UTF8MB4_GENERAL_CI,
  `test_out_risk_level` varchar(128) NULL COMMENT "准出阶段回溯风险等级" COLLATE UTF8MB4_GENERAL_CI,
  `test_out_risk_score` varchar(128) NULL COMMENT "准出阶段回溯风险分" COLLATE UTF8MB4_GENERAL_CI,
  `runtime_out_risk_level` varchar(128) NULL COMMENT "准出阶段实时风险等级" COLLATE UTF8MB4_GENERAL_CI,
  `runtime_out_risk_score` varchar(128) NULL COMMENT "准出阶段实时风险分" COLLATE UTF8MB4_GENERAL_CI,
  `test_in_addition_cov_rate` double NULL COMMENT "提测阶段boe覆盖率",
  `test_in_tes_cov` double NULL COMMENT "提测阶段tes覆盖率",
  `test_in_p0p1_case_cov` double NULL COMMENT "提测阶段p0p1case覆盖率",
  `test_in_satcheck_rate` double NULL COMMENT "提测阶段satcheck成功率",
  `test_in_tesla_storehouse_rate` double NULL COMMENT "提测阶段tesla仓库模式成功率",
  `test_in_top10_api_cov` json NULL COMMENT "提测阶段top10影响接口覆盖率",
  `test_in_tesla_cov` double NULL COMMENT "提测阶段tesla覆盖率",
  `test_in_ftf_cov` double NULL COMMENT "提测阶段ftf覆盖率",
  `test_in_autotest_full_cov` double NULL COMMENT "提测泛自动化全量覆盖率",
  `test_in_autotest_diff_cov` double NULL COMMENT "提测泛自动化增量覆盖率",
  `test_in_result` int(11) NULL COMMENT "提测结果",
  `test_out_addition_cov_rate` double NULL COMMENT "准出boe增量覆盖率",
  `test_out_tes_cov` double NULL COMMENT "准出tes覆盖率",
  `test_out_p0p1_case_cov` double NULL COMMENT "准出p0p1case覆盖率",
  `test_out_satcheck_rate` double NULL COMMENT "准出satcheck成功率",
  `test_out_tesla_storehouse_rate` double NULL COMMENT "准出tesla仓库模式成功率",
  `test_out_top10_api_cov` double NULL COMMENT "准出top10影响接口覆盖率",
  `test_out_tesla_cov` double NULL COMMENT "准出tesla覆盖率",
  `test_out_ftf_cov` double NULL COMMENT "准出阶段ftf覆盖率",
  `test_out_autotest_full_cov` json NULL COMMENT "准出泛自动化全量覆盖率",
  `test_out_autotest_diff_cov` json NULL COMMENT "准出泛自动化增量覆盖率",
  `test_out_result` int(11) NULL COMMENT "准出结果",
  `test_in_ut_cov` double NULL COMMENT "提测ut覆盖率",
  `test_out_ut_cov` double NULL COMMENT "准出ut覆盖率",
  `tes_case_count` int(11) NULL COMMENT "tes创建case数量",
  `reserved_1` varchar(128) NULL COMMENT "预留字段" COLLATE UTF8MB4_GENERAL_CI,
  `reserved_2` varchar(128) NULL COMMENT "预留字段" COLLATE UTF8MB4_GENERAL_CI,
  `reserved_3` varchar(128) NULL COMMENT "预留字段" COLLATE UTF8MB4_GENERAL_CI,
  `reserved_4` varchar(128) NULL COMMENT "预留字段" COLLATE UTF8MB4_GENERAL_CI,
  `reserved_5` double NULL COMMENT "预留字段",
  `reserved_6` double NULL COMMENT "预留字段",
  `reserved_7` double NULL COMMENT "预留字段",
  `reserved_8` double NULL COMMENT "预留字段"
);

CREATE TABLE `public_bug_dwd_d` (
  `bug_fix_time` datetime NULL COMMENT "bug解决时间",
  `is_delete` bigint(20) NULL COMMENT "是否已删除",
  `assignee` varchar(64) NULL COMMENT "修复bug的人" COLLATE UTF8MB4_GENERAL_CI,
  `project_key` varchar(64) NULL COMMENT "项目key" COLLATE UTF8MB4_GENERAL_CI,
  `id` bigint(20) NULL COMMENT "主键自增ID",
  `date` datetime NULL COMMENT "分区",
  `bug_id` bigint(20) NULL COMMENT "bug id",
  `bug_name` varchar(500) NULL COMMENT "标题" COLLATE UTF8MB4_GENERAL_CI,
  `bug_url` varchar(200) NULL COMMENT "bug链接" COLLATE UTF8MB4_GENERAL_CI,
  `priority` varchar(32) NULL COMMENT "bug优先级" COLLATE UTF8MB4_GENERAL_CI,
  `bug_status` varchar(64) NULL COMMENT "bug状态" COLLATE UTF8MB4_GENERAL_CI,
  `status_log` varchar(65533) NULL COMMENT "状态变更记录" COLLATE UTF8MB4_GENERAL_CI,
  `requirement_url` varchar(200) NULL COMMENT "bug关联的需求链接" COLLATE UTF8MB4_GENERAL_CI,
  `find_stage` varchar(64) NULL COMMENT "bug发现阶段" COLLATE UTF8MB4_GENERAL_CI,
  `import_cause` varchar(64) NULL COMMENT "bug引入原因" COLLATE UTF8MB4_GENERAL_CI,
  `category` varchar(64) NULL COMMENT "缺陷类型" COLLATE UTF8MB4_GENERAL_CI,
  `find_way` varchar(64) NULL COMMENT "bug发现手段" COLLATE UTF8MB4_GENERAL_CI,
  `module` varchar(64) NULL COMMENT "bug一级模块" COLLATE UTF8MB4_GENERAL_CI,
  `functional_module` varchar(64) NULL COMMENT "bug功能模块" COLLATE UTF8MB4_GENERAL_CI,
  `avoid_way` varchar(64) NULL COMMENT "避免手段" COLLATE UTF8MB4_GENERAL_CI,
  `test_env` varchar(32) NULL COMMENT "测试环境" COLLATE UTF8MB4_GENERAL_CI,
  `is_first_round` bigint(20) NULL COMMENT "是否首轮bug",
  `resolution` varchar(64) NULL COMMENT "解决方案" COLLATE UTF8MB4_GENERAL_CI,
  `biz` bigint(20) NULL COMMENT "rocket biz id",
  `project_space` varchar(64) NULL COMMENT "项目空间" COLLATE UTF8MB4_GENERAL_CI,
  `platform` varchar(32) NULL COMMENT "系统类型" COLLATE UTF8MB4_GENERAL_CI,
  `find_version` varchar(128) NULL COMMENT "发现版本" COLLATE UTF8MB4_GENERAL_CI,
  `import_version` varchar(128) NULL COMMENT "引入版本" COLLATE UTF8MB4_GENERAL_CI,
  `fix_version` varchar(128) NULL COMMENT "解决版本" COLLATE UTF8MB4_GENERAL_CI,
  `probability` varchar(32) NULL COMMENT "bug发生概率" COLLATE UTF8MB4_GENERAL_CI,
  `business_importance` varchar(32) NULL COMMENT "业务重要程度" COLLATE UTF8MB4_GENERAL_CI,
  `severity` varchar(32) NULL COMMENT "问题严重程度" COLLATE UTF8MB4_GENERAL_CI,
  `trigger_strategy` varchar(64) NULL COMMENT "触发策略" COLLATE UTF8MB4_GENERAL_CI,
  `stability_classify` varchar(64) NULL COMMENT "稳定性细分" COLLATE UTF8MB4_GENERAL_CI,
  `reporter` varchar(64) NULL COMMENT "提交bug的人" COLLATE UTF8MB4_GENERAL_CI,
  `relevant_person` varchar(64) NULL COMMENT "相关人" COLLATE UTF8MB4_GENERAL_CI,
  `rd_business` varchar(64) NULL COMMENT "研发所属业务线" COLLATE UTF8MB4_GENERAL_CI,
  `preprocess_source_version` varchar(64) NULL COMMENT "用户预处理字段：数据源版本" COLLATE UTF8MB4_GENERAL_CI,
  `preprocess_requirement_version` varchar(64) NULL COMMENT "用户预处理字段：bug所属需求绑定版本" COLLATE UTF8MB4_GENERAL_CI,
  `preprocess_requirement_type` varchar(64) NULL COMMENT "用户预处理字段：bug所属需求类型" COLLATE UTF8MB4_GENERAL_CI,
  `preprocess_is_stable` bigint(20) NULL COMMENT "用户预处理字段：是否稳定性bug",
  `preprocess_find_duration` bigint(20) NULL COMMENT "用户预处理字段：bug发现时长, 单位为秒",
  `preprocess_fix_duration` bigint(20) NULL COMMENT "用户预处理字段：bug修复时长, 单位为秒",
  `preprocess_close_duration` bigint(20) NULL COMMENT "用户预处理字段：bug关闭时长, 单位为秒",
  `preprocess_rd_dispose_duration` bigint(20) NULL COMMENT "用户预处理字段：rd bug处理时长, 单位为秒",
  `preprocess_rd_response_duration` bigint(20) NULL COMMENT "用户预处理字段：rd bug响应时长, 单位为秒",
  `tags` varchar(64) NULL COMMENT "标签" COLLATE UTF8MB4_GENERAL_CI,
  `bug_create_time` datetime NULL COMMENT "bug创建时间",
  `bug_update_time` datetime NULL COMMENT "bug创建时间",
  `rid` bigint(20) NULL COMMENT "需求id",
  `jira_project_id` bigint(20) NULL COMMENT "jira项目id",
  `jira_key` varchar(32) NULL COMMENT "jira bug key" COLLATE UTF8MB4_GENERAL_CI,
  `source` varchar(32) NULL COMMENT "来源于Rocket jira bits" COLLATE UTF8MB4_GENERAL_CI,
  `resolution_date` datetime NULL COMMENT "解决时间",
  `ext1` varchar(200) NULL COMMENT "用户特有字段1" COLLATE UTF8MB4_GENERAL_CI,
  `ext2` varchar(200) NULL COMMENT "用户特有字段2" COLLATE UTF8MB4_GENERAL_CI,
  `ext3` varchar(200) NULL COMMENT "用户特有字段3" COLLATE UTF8MB4_GENERAL_CI,
  `ext4` varchar(200) NULL COMMENT "用户特有字段4" COLLATE UTF8MB4_GENERAL_CI,
  `ext5` varchar(32) NULL COMMENT "自定义字段5" COLLATE UTF8MB4_GENERAL_CI,
  `ext6` varchar(32) NULL COMMENT "自定义字段6" COLLATE UTF8MB4_GENERAL_CI,
  `ext7` varchar(32) NULL COMMENT "自定义字段7" COLLATE UTF8MB4_GENERAL_CI,
  `ext8` varchar(32) NULL COMMENT "自定义字段8" COLLATE UTF8MB4_GENERAL_CI,
  `dept_full_name` varchar(128) NULL COMMENT "经办人所属的部门" COLLATE UTF8MB4_GENERAL_CI,
  `reporter_dept_full_name` varchar(128) NULL COMMENT "提交人所属部门" COLLATE UTF8MB4_GENERAL_CI,
  `create_time` datetime NULL COMMENT "创建时间",
  `update_time` datetime NULL COMMENT "更新时间",
  `source_bug_id` varchar(64) NULL COMMENT "{source}_{bug_id}" COLLATE UTF8MB4_GENERAL_CI,
  `bug_start_fix_time` datetime NULL COMMENT "bug开始修复时间",
  `bug_close_time` datetime NULL COMMENT "bug关闭时间",
  `bug_last_reopen_time` datetime NULL COMMENT "最后一次Reopen时间",
  `reopen_cnt` bigint(20) NULL COMMENT "reopen次数",
  `requirement_name` varchar(200) NULL COMMENT "需求名称" COLLATE UTF8MB4_GENERAL_CI,
  `is_consume` bigint(20) NULL COMMENT "是否消费",
  `preprocess_version_month` varchar(32) NULL COMMENT "导出版本月归属" COLLATE UTF8MB4_GENERAL_CI,
  `second_level_module` varchar(64) NULL COMMENT "二级模块" COLLATE UTF8MB4_GENERAL_CI,
  `third_level_module` varchar(64) NULL COMMENT "三级模块" COLLATE UTF8MB4_GENERAL_CI,
  `root_cause` varchar(512) NULL COMMENT "缺陷根本原因" COLLATE UTF8MB4_GENERAL_CI,
  `reappear_path` varchar(512) NULL COMMENT "缺陷复现路径" COLLATE UTF8MB4_GENERAL_CI,
  `how_to_prevent` varchar(512) NULL COMMENT "缺陷如何避免发生" COLLATE UTF8MB4_GENERAL_CI,
  `rd_resolve_result` varchar(128) NULL COMMENT "RD解决结果" COLLATE UTF8MB4_GENERAL_CI,
  `qa_confirm_result` varchar(128) NULL COMMENT "QA确认结果" COLLATE UTF8MB4_GENERAL_CI,
  `rd_cause_reopen_cnt` bigint(20) NULL COMMENT "rd原因导致的reopen次数",
  `qa_cause_reopen_cnt` bigint(20) NULL COMMENT "qa原因导致的reopen次数",
  `preprocess_is_fix_before_grey` bigint(20) NULL COMMENT "是否是版本灰度前修复",
  `business` varchar(128) NULL COMMENT "缺陷所属业务线" COLLATE UTF8MB4_GENERAL_CI,
  `business_ids` varchar(512) NULL COMMENT "业务线ID, id1/id2" COLLATE UTF8MB4_GENERAL_CI,
  `is_target_scene` varchar(64) NULL COMMENT "是否为目标场景" COLLATE UTF8MB4_GENERAL_CI,
  `requirement_state` varchar(32) NULL COMMENT "需求状态" COLLATE UTF8MB4_GENERAL_CI,
  `template_type` varchar(32) NULL COMMENT "缺陷模板类型" COLLATE UTF8MB4_GENERAL_CI,
  `rd_attribution` varchar(256) NULL COMMENT "研发环节归因/研发归因" COLLATE UTF8MB4_GENERAL_CI,
  `test_attribution` varchar(256) NULL COMMENT "测试环节归因/测试归因" COLLATE UTF8MB4_GENERAL_CI,
  `planning_sprint` varchar(256) NULL COMMENT "规划迭代" COLLATE UTF8MB4_GENERAL_CI,
  `orientation` varchar(256) NULL COMMENT "缺陷归属方向" COLLATE UTF8MB4_GENERAL_CI,
  `security_question_type` varchar(256) NULL COMMENT "安全问题类型" COLLATE UTF8MB4_GENERAL_CI,
  `ext9` varchar(64) NULL COMMENT "自定义字段9" COLLATE UTF8MB4_GENERAL_CI,
  `ext10` varchar(64) NULL COMMENT "自定义字段10" COLLATE UTF8MB4_GENERAL_CI,
  `ext11` varchar(64) NULL COMMENT "自定义字段11" COLLATE UTF8MB4_GENERAL_CI,
  `ext12` varchar(64) NULL COMMENT "自定义字段12" COLLATE UTF8MB4_GENERAL_CI,
  `ext13` varchar(64) NULL COMMENT "自定义字段13" COLLATE UTF8MB4_GENERAL_CI,
  `ext14` varchar(64) NULL COMMENT "自定义字段14" COLLATE UTF8MB4_GENERAL_CI,
  `ext15` varchar(64) NULL COMMENT "自定义字段15" COLLATE UTF8MB4_GENERAL_CI,
  `ext16` varchar(64) NULL COMMENT "自定义字段16" COLLATE UTF8MB4_GENERAL_CI,
  `ext17` varchar(64) NULL COMMENT "自定义字段17" COLLATE UTF8MB4_GENERAL_CI,
  `ext18` varchar(64) NULL COMMENT "自定义字段18" COLLATE UTF8MB4_GENERAL_CI,
  `ext19` varchar(64) NULL COMMENT "自定义字段19" COLLATE UTF8MB4_GENERAL_CI,
  `ext20` varchar(64) NULL COMMENT "自定义字段20" COLLATE UTF8MB4_GENERAL_CI,
  `new_or_old_classify` varchar(64) NULL COMMENT "新老功能分类" COLLATE UTF8MB4_GENERAL_CI,
  `test_free_bug` varchar(64) NULL COMMENT "是否免测需求Bug" COLLATE UTF8MB4_GENERAL_CI,
  `rd_improve` varchar(128) NULL COMMENT "研发改进方向" COLLATE UTF8MB4_GENERAL_CI,
  `qa_improve` varchar(128) NULL COMMENT "测试改进方向" COLLATE UTF8MB4_GENERAL_CI,
  `unrecall_bug_reason` varchar(128) NULL COMMENT "未召回问题原因" COLLATE UTF8MB4_GENERAL_CI,
  `is_old_scene` varchar(128) NULL COMMENT "是否为存量场景" COLLATE UTF8MB4_GENERAL_CI,
  `fix_mr` varchar(128) NULL COMMENT "修复Bug的MR" COLLATE UTF8MB4_GENERAL_CI,
  `import_mr` varchar(128) NULL COMMENT "引入Bug的MR" COLLATE UTF8MB4_GENERAL_CI,
  `relation_pipeline` varchar(128) NULL COMMENT "Bug关联的流水线ID" COLLATE UTF8MB4_GENERAL_CI,
  `standard_not_intercept_reason` varchar(128) NULL COMMENT "准入准出/规范发布专项未拦截原因" COLLATE UTF8MB4_GENERAL_CI,
  `test_leaker` varchar(128) NULL COMMENT "漏测责任人" COLLATE UTF8MB4_GENERAL_CI,
  `intercept_scene_type` varchar(128) NULL COMMENT "缺陷拦截的场景类型" COLLATE UTF8MB4_GENERAL_CI,
  `monitor_improvement` varchar(128) NULL COMMENT "监控改进字段 " COLLATE UTF8MB4_GENERAL_CI,
  `ext21` varchar(65533) NULL COMMENT "自定义字段21" COLLATE UTF8MB4_GENERAL_CI,
  `ext22` varchar(65533) NULL COMMENT "自定义字段22" COLLATE UTF8MB4_GENERAL_CI,
  `ext23` varchar(65533) NULL COMMENT "自定义字段23" COLLATE UTF8MB4_GENERAL_CI,
  `ext24` varchar(65533) NULL COMMENT "自定义字段24" COLLATE UTF8MB4_GENERAL_CI,
  `ext25` varchar(65533) NULL COMMENT "自定义字段25" COLLATE UTF8MB4_GENERAL_CI,
  `ext26` varchar(65533) NULL COMMENT "自定义字段26" COLLATE UTF8MB4_GENERAL_CI,
  `ext27` varchar(65533) NULL COMMENT "自定义字段27" COLLATE UTF8MB4_GENERAL_CI,
  `ext28` varchar(65533) NULL COMMENT "自定义字段28" COLLATE UTF8MB4_GENERAL_CI,
  `ext29` varchar(65533) NULL COMMENT "自定义字段29" COLLATE UTF8MB4_GENERAL_CI,
  `ext30` varchar(65533) NULL COMMENT "自定义字段30" COLLATE UTF8MB4_GENERAL_CI,
  `ext31` varchar(65533) NULL COMMENT "自定义字段31" COLLATE UTF8MB4_GENERAL_CI,
  `ext32` varchar(65533) NULL COMMENT "自定义字段32" COLLATE UTF8MB4_GENERAL_CI,
  `ext33` varchar(65533) NULL COMMENT "自定义字段33" COLLATE UTF8MB4_GENERAL_CI,
  `ext34` varchar(65533) NULL COMMENT "自定义字段34" COLLATE UTF8MB4_GENERAL_CI,
  `ext35` varchar(65533) NULL COMMENT "自定义字段35" COLLATE UTF8MB4_GENERAL_CI,
  `ext36` varchar(65533) NULL COMMENT "自定义字段36" COLLATE UTF8MB4_GENERAL_CI,
  `ext37` varchar(65533) NULL COMMENT "自定义字段37" COLLATE UTF8MB4_GENERAL_CI,
  `ext38` varchar(65533) NULL COMMENT "自定义字段38" COLLATE UTF8MB4_GENERAL_CI,
  `ext39` varchar(65533) NULL COMMENT "自定义字段39" COLLATE UTF8MB4_GENERAL_CI,
  `ext40` varchar(65533) NULL COMMENT "自定义字段40" COLLATE UTF8MB4_GENERAL_CI,
  `ext41` varchar(65533) NULL COMMENT "自定义字段41" COLLATE UTF8MB4_GENERAL_CI,
  `ext42` varchar(65533) NULL COMMENT "自定义字段42" COLLATE UTF8MB4_GENERAL_CI,
  `ext43` varchar(65533) NULL COMMENT "自定义字段43" COLLATE UTF8MB4_GENERAL_CI,
  `ext44` varchar(65533) NULL COMMENT "自定义字段44" COLLATE UTF8MB4_GENERAL_CI,
  `ext45` varchar(65533) NULL COMMENT "自定义字段45" COLLATE UTF8MB4_GENERAL_CI,
  `ext46` varchar(65533) NULL COMMENT "自定义字段46" COLLATE UTF8MB4_GENERAL_CI,
  `ext47` varchar(65533) NULL COMMENT "自定义字段47" COLLATE UTF8MB4_GENERAL_CI,
  `ext48` varchar(65533) NULL COMMENT "自定义字段48" COLLATE UTF8MB4_GENERAL_CI,
  `ext49` varchar(65533) NULL COMMENT "自定义字段49" COLLATE UTF8MB4_GENERAL_CI,
  `ext50` varchar(65533) NULL COMMENT "自定义字段50" COLLATE UTF8MB4_GENERAL_CI,
  `ext51` varchar(65533) NULL COMMENT "自定义字段51" COLLATE UTF8MB4_GENERAL_CI,
  `ext52` varchar(65533) NULL COMMENT "自定义字段52" COLLATE UTF8MB4_GENERAL_CI,
  `ext53` varchar(65533) NULL COMMENT "自定义字段53" COLLATE UTF8MB4_GENERAL_CI,
  `ext54` varchar(65533) NULL COMMENT "自定义字段54" COLLATE UTF8MB4_GENERAL_CI,
  `ext55` varchar(65533) NULL COMMENT "自定义字段55" COLLATE UTF8MB4_GENERAL_CI,
  `ext56` varchar(65533) NULL COMMENT "自定义字段56" COLLATE UTF8MB4_GENERAL_CI,
  `ext57` varchar(65533) NULL COMMENT "自定义字段57" COLLATE UTF8MB4_GENERAL_CI,
  `ext58` varchar(65533) NULL COMMENT "自定义字段58" COLLATE UTF8MB4_GENERAL_CI,
  `ext59` varchar(65533) NULL COMMENT "自定义字段59" COLLATE UTF8MB4_GENERAL_CI,
  `ext60` varchar(65533) NULL COMMENT "自定义字段60" COLLATE UTF8MB4_GENERAL_CI,
  `test_improve_risk` varchar(255) NULL COMMENT "测改FT_风险标签" COLLATE UTF8MB4_GENERAL_CI,
  `test_improve_improving` varchar(255) NULL COMMENT "测改FT_改进标签" COLLATE UTF8MB4_GENERAL_CI,
  `test_improve_reason` varchar(255) NULL COMMENT "测改FT_归因标签" COLLATE UTF8MB4_GENERAL_CI,
  `test_improve_bug_type` varchar(255) NULL COMMENT "测改FT_缺陷类型" COLLATE UTF8MB4_GENERAL_CI,
  `ext61` varchar(65533) NULL COMMENT "自定义字段61" COLLATE UTF8MB4_GENERAL_CI,
  `ext62` varchar(65533) NULL COMMENT "自定义字段62" COLLATE UTF8MB4_GENERAL_CI,
  `ext63` varchar(65533) NULL COMMENT "自定义字段63" COLLATE UTF8MB4_GENERAL_CI,
  `ext64` varchar(65533) NULL COMMENT "自定义字段64" COLLATE UTF8MB4_GENERAL_CI,
  `ext65` varchar(65533) NULL COMMENT "自定义字段65" COLLATE UTF8MB4_GENERAL_CI,
  `ext66` varchar(65533) NULL COMMENT "自定义字段66" COLLATE UTF8MB4_GENERAL_CI,
  `ext67` varchar(65533) NULL COMMENT "自定义字段67" COLLATE UTF8MB4_GENERAL_CI,
  `ext68` varchar(65533) NULL COMMENT "自定义字段68" COLLATE UTF8MB4_GENERAL_CI,
  `ext69` varchar(65533) NULL COMMENT "自定义字段69" COLLATE UTF8MB4_GENERAL_CI,
  `ext70` varchar(65533) NULL COMMENT "自定义字段70" COLLATE UTF8MB4_GENERAL_CI,
  `ext71` varchar(65533) NULL COMMENT "自定义字段71" COLLATE UTF8MB4_GENERAL_CI,
  `ext72` varchar(65533) NULL COMMENT "自定义字段72" COLLATE UTF8MB4_GENERAL_CI,
  `ext73` varchar(65533) NULL COMMENT "自定义字段73" COLLATE UTF8MB4_GENERAL_CI,
  `ext74` varchar(65533) NULL COMMENT "自定义字段74" COLLATE UTF8MB4_GENERAL_CI,
  `ext75` varchar(65533) NULL COMMENT "自定义字段75" COLLATE UTF8MB4_GENERAL_CI,
  `ext76` varchar(65533) NULL COMMENT "自定义字段76" COLLATE UTF8MB4_GENERAL_CI,
  `ext77` varchar(65533) NULL COMMENT "自定义字段77" COLLATE UTF8MB4_GENERAL_CI,
  `ext78` varchar(65533) NULL COMMENT "自定义字段78" COLLATE UTF8MB4_GENERAL_CI,
  `ext79` varchar(65533) NULL COMMENT "自定义字段79" COLLATE UTF8MB4_GENERAL_CI,
  `ext80` varchar(65533) NULL COMMENT "自定义字段80" COLLATE UTF8MB4_GENERAL_CI,
  `ext81` varchar(65533) NULL COMMENT "自定义字段81" COLLATE UTF8MB4_GENERAL_CI,
  `ext82` varchar(65533) NULL COMMENT "自定义字段82" COLLATE UTF8MB4_GENERAL_CI,
  `ext83` varchar(65533) NULL COMMENT "自定义字段83" COLLATE UTF8MB4_GENERAL_CI,
  `ext84` varchar(65533) NULL COMMENT "自定义字段84" COLLATE UTF8MB4_GENERAL_CI,
  `ext85` varchar(65533) NULL COMMENT "自定义字段85" COLLATE UTF8MB4_GENERAL_CI,
  `bug_commit_loc` bigint(20) NULL COMMENT "bug_commit_loc",
  `ext86` varchar(65533) NULL COMMENT "自定义字段86" COLLATE UTF8MB4_GENERAL_CI,
  `ext87` varchar(65533) NULL COMMENT "自定义字段87" COLLATE UTF8MB4_GENERAL_CI,
  `ext88` varchar(65533) NULL COMMENT "自定义字段88" COLLATE UTF8MB4_GENERAL_CI,
  `ext89` varchar(65533) NULL COMMENT "自定义字段89" COLLATE UTF8MB4_GENERAL_CI,
  `ext90` varchar(65533) NULL COMMENT "自定义字段90" COLLATE UTF8MB4_GENERAL_CI,
  `rqm_type` varchar(65533) NULL COMMENT "关联需求类型" COLLATE UTF8MB4_GENERAL_CI,
  `rqm_business_line` varchar(65533) NULL COMMENT "关联需求业务线" COLLATE UTF8MB4_GENERAL_CI,
  `business_line_1` varchar(65533) NULL COMMENT "关联需求一级业务线" COLLATE UTF8MB4_GENERAL_CI,
  `business_line_2` varchar(65533) NULL COMMENT "关联需求二级业务线" COLLATE UTF8MB4_GENERAL_CI,
  `business_line_3` varchar(65533) NULL COMMENT "关联需求三级业务线" COLLATE UTF8MB4_GENERAL_CI,
  `release_version` varchar(65533) NULL COMMENT "关联需求发布版本" COLLATE UTF8MB4_GENERAL_CI,
  `plan_version` varchar(65533) NULL COMMENT "关联需求规划版本" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_1` varchar(65533) NULL COMMENT "关联需求自定义字段1" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_2` varchar(65533) NULL COMMENT "关联需求自定义字段2" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_3` varchar(65533) NULL COMMENT "关联需求自定义字段3" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_4` varchar(65533) NULL COMMENT "关联需求自定义字段4" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_5` varchar(65533) NULL COMMENT "关联需求自定义字段5" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_6` varchar(65533) NULL COMMENT "关联需求自定义字段6" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_7` varchar(65533) NULL COMMENT "关联需求自定义字段7" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_8` varchar(65533) NULL COMMENT "关联需求自定义字段8" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_9` varchar(65533) NULL COMMENT "关联需求自定义字段9" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_10` varchar(65533) NULL COMMENT "关联需求自定义字段10" COLLATE UTF8MB4_GENERAL_CI,
  `test_method` varchar(65533) NULL COMMENT "关联需求测试方式" COLLATE UTF8MB4_GENERAL_CI,
  `space_id` varchar(65533) NULL COMMENT "关联需求所属空间ID" COLLATE UTF8MB4_GENERAL_CI,
  `rqm_tag` varchar(65533) NULL COMMENT "关联需求标签" COLLATE UTF8MB4_GENERAL_CI,
  `rqm_priority` varchar(65533) NULL COMMENT "关联需求优先级" COLLATE UTF8MB4_GENERAL_CI,
  `qa_members` varchar(65533) NULL COMMENT "关联需求qa成员" COLLATE UTF8MB4_GENERAL_CI,
  `lark_release_version` varchar(65533) NULL COMMENT "关联需求实际合入版本（总）lark" COLLATE UTF8MB4_GENERAL_CI,
  `ea_is_qa` varchar(65533) NULL COMMENT "关联需求QA是否介入（EA）" COLLATE UTF8MB4_GENERAL_CI,
  `ea_tech_difficulty` varchar(65533) NULL COMMENT "关联需求技术难度（EA）" COLLATE UTF8MB4_GENERAL_CI,
  `ea_case_completeness_score` varchar(65533) NULL COMMENT "关联需求测试用例完备度评分（EA）" COLLATE UTF8MB4_GENERAL_CI,
  `ea_rqm_type` varchar(65533) NULL COMMENT "关联需求类型（EA）" COLLATE UTF8MB4_GENERAL_CI,
  `ea_correlation_story` varchar(65533) NULL COMMENT "关联需求所属story（EA）" COLLATE UTF8MB4_GENERAL_CI,
  `ea_correlation_toplist` varchar(65533) NULL COMMENT "关联需求所属toplist（EA）" COLLATE UTF8MB4_GENERAL_CI,
  `ea_correlation_epic` varchar(65533) NULL COMMENT "关联需求epic（EA）" COLLATE UTF8MB4_GENERAL_CI,
  `lark_rqm_type` varchar(65533) NULL COMMENT "关联需求类型（lark）" COLLATE UTF8MB4_GENERAL_CI,
  `employee_type` varchar(65533) NULL COMMENT "关联人员报告人类型" COLLATE UTF8MB4_GENERAL_CI,
  `city` varchar(65533) NULL COMMENT "关联人员报告人base城市" COLLATE UTF8MB4_GENERAL_CI,
  `country` varchar(65533) NULL COMMENT "关联人员报告人base国家" COLLATE UTF8MB4_GENERAL_CI,
  `sequence` varchar(65533) NULL COMMENT "关联人员报告人序列" COLLATE UTF8MB4_GENERAL_CI,
  `employee_type_2` varchar(65533) NULL COMMENT "关联人员经办人类型" COLLATE UTF8MB4_GENERAL_CI,
  `city_2` varchar(65533) NULL COMMENT "关联人员经办人base城市" COLLATE UTF8MB4_GENERAL_CI,
  `country_2` varchar(65533) NULL COMMENT "关联人员经办人base国家" COLLATE UTF8MB4_GENERAL_CI,
  `sequence_2` varchar(65533) NULL COMMENT "关联人员经办人序列" COLLATE UTF8MB4_GENERAL_CI,
  `job_category_2` varchar(65533) NULL COMMENT "关联人员经办人工作方向" COLLATE UTF8MB4_GENERAL_CI,
  `is_terminated_2` bigint(20) NULL COMMENT "关联人员经办人是否离职",
  `is_leader` bigint(20) NULL COMMENT "关联人员报告人是否是Leader",
  `leader_name` varchar(65533) NULL COMMENT "关联人员报告人Leader邮箱前缀" COLLATE UTF8MB4_GENERAL_CI,
  `is_leader_2` bigint(20) NULL COMMENT "关联人员经办人是否是Leader",
  `leader_name_2` varchar(65533) NULL COMMENT "关联人员经办人Leader邮箱前缀" COLLATE UTF8MB4_GENERAL_CI,
  `employee_type_3` varchar(65533) NULL COMMENT "关联人员漏测责任人雇员类型" COLLATE UTF8MB4_GENERAL_CI,
  `dept_full_name_3` varchar(65533) NULL COMMENT "关联人员漏测责任人部门" COLLATE UTF8MB4_GENERAL_CI,
  `source_id` bigint(20) NULL COMMENT "关联TT阶段时间source_id",
  `source_type` varchar(65533) NULL COMMENT "关联TT阶段时间类型" COLLATE UTF8MB4_GENERAL_CI,
  `filter_id` bigint(20) NULL COMMENT "关联jira issue过滤id",
  `language_name` varchar(65533) NULL COMMENT "关联Meggo仓库语言" COLLATE UTF8MB4_GENERAL_CI,
  `priority_changed` bigint(20) NULL COMMENT "关联缺陷过去31天是否发生优先级变更(天粒度)",
  `priority_set` varchar(65533) NULL COMMENT "关联缺陷过去31天优先级集合(天粒度)" COLLATE UTF8MB4_GENERAL_CI,
  `main_node_str` varchar(65533) NULL COMMENT "关联业务映射缺陷归属业务线" COLLATE UTF8MB4_GENERAL_CI,
  `reporter_dept_full_path` varchar(65533) NULL COMMENT "关联部门报告人当前部门" COLLATE UTF8MB4_GENERAL_CI,
  `assignee_dept_full_path` varchar(65533) NULL COMMENT "关联部门经办人当前部门" COLLATE UTF8MB4_GENERAL_CI,
  `rqm_create_time` datetime NULL DEFAULT NULL COMMENT "关联需求创建时间",
  `test_start_time` datetime NULL DEFAULT NULL COMMENT "关联需求测试开始时间",
  `test_end_time` datetime NULL DEFAULT NULL COMMENT "关联需求测试完成时间",
  `release_start_time` datetime NULL DEFAULT NULL COMMENT "关联需求发布开始时间",
  `release_end_time` datetime NULL DEFAULT NULL COMMENT "关联需求发布完成时间",
  `milestone_3_time` datetime NULL DEFAULT NULL COMMENT "关联需求第3号里程碑时间",
  `rqm_lark_create_time` datetime NULL DEFAULT NULL COMMENT "关联需求发布时间（lark）",
  `lark_bug_cnt_t` datetime NULL DEFAULT NULL COMMENT "关联需求关联千行BUG数时间维度（LPE定制）",
  `entry_time` datetime NULL DEFAULT NULL COMMENT "关联人员报告人入职时间",
  `entry_time_2` datetime NULL DEFAULT NULL COMMENT "关联人员经办人入职时间",
  `os_test_end_time_level2` datetime NULL DEFAULT NULL COMMENT "关联需求分端需求测试完成时间(single_table)",
  `dev_start_time` datetime NULL DEFAULT NULL COMMENT "关联需求研发开始时间",
  `dev_end_time` datetime NULL DEFAULT NULL COMMENT "关联需求研发完成时间",
  `bug_status_name` varchar(1500) NULL DEFAULT "" COMMENT "bug状态名称" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_13` varchar(65533) NULL DEFAULT NULL COMMENT "关联需求自定义字段13" COLLATE UTF8MB4_GENERAL_CI,
  `ext91` varchar(65533) NULL DEFAULT NULL COMMENT "自定义字段91" COLLATE UTF8MB4_GENERAL_CI,
  `ext92` varchar(65533) NULL DEFAULT NULL COMMENT "自定义字段92" COLLATE UTF8MB4_GENERAL_CI,
  `ext93` varchar(65533) NULL DEFAULT NULL COMMENT "自定义字段93" COLLATE UTF8MB4_GENERAL_CI,
  `ext94` varchar(65533) NULL DEFAULT NULL COMMENT "自定义字段94" COLLATE UTF8MB4_GENERAL_CI,
  `ext95` varchar(65533) NULL DEFAULT NULL COMMENT "自定义字段95" COLLATE UTF8MB4_GENERAL_CI,
  `ext96` varchar(65533) NULL DEFAULT NULL COMMENT "自定义字段96" COLLATE UTF8MB4_GENERAL_CI,
  `ext97` varchar(65533) NULL DEFAULT NULL COMMENT "自定义字段97" COLLATE UTF8MB4_GENERAL_CI,
  `ext98` varchar(65533) NULL DEFAULT NULL COMMENT "自定义字段98" COLLATE UTF8MB4_GENERAL_CI,
  `ext99` varchar(65533) NULL DEFAULT NULL COMMENT "自定义字段99" COLLATE UTF8MB4_GENERAL_CI,
  `ext100` varchar(65533) NULL DEFAULT NULL COMMENT "自定义字段100" COLLATE UTF8MB4_GENERAL_CI,
  `assignee_create_report_full_path` varchar(256) NULL DEFAULT NULL COMMENT "经办人创建时间汇报线路径" COLLATE UTF8MB4_GENERAL_CI,
  `assignee_fix_report_full_path` varchar(256) NULL DEFAULT "" COMMENT "经办人修复时间汇报线路径" COLLATE UTF8MB4_GENERAL_CI,
  `reporter_create_report_full_path` varchar(256) NULL DEFAULT "" COMMENT "报告人创建时间汇报线路径" COLLATE UTF8MB4_GENERAL_CI,
  `assignee_test_end_report_full_path` varchar(256) NULL DEFAULT NULL COMMENT "成员测试完成时间汇报线路径" COLLATE UTF8MB4_GENERAL_CI,
  `reporter_test_end_report_full_path` varchar(256) NULL DEFAULT NULL COMMENT "成员测试开始时间汇报线路径" COLLATE UTF8MB4_GENERAL_CI
);

CREATE TABLE `public_department_version_ods_h` (
  `dept_id` bigint(20) NULL COMMENT "部门id",
  `pid` bigint(20) NULL COMMENT "父节点/上级部门dept_id",
  `effective_time` datetime NULL COMMENT "版本生效时间",
  `is_delete` int(11) NULL COMMENT "是否删除",
  `date` datetime NULL COMMENT "分区时间",
  `id` bigint(20) NULL COMMENT "主键自增ID",
  `version_id` bigint(20) NULL COMMENT "部门版本ID",
  `dept_full_path` varchar(65533) NULL COMMENT "真实部门全路径：/000001/000002/000003",
  `dept_full_name_path` varchar(65533) NULL COMMENT "真实部门全路径：/pdi/pdi-dev inf/pdi-dev inf-devmind",
  `dept_full_name` varchar(65533) NULL COMMENT "部门全名：产品研发和工程架构部-Client Infrastructure-APM",
  `dept_full_name_en` varchar(65533) NULL COMMENT "部门英文全名",
  `expiry_time` datetime NULL COMMENT "版本失效时间",
  `is_name_change` int(11) NULL COMMENT "是否名称变动",
  `is_name_en_change` int(11) NULL COMMENT "是否英文名称变动",
  `is_node_change` int(11) NULL COMMENT "是否节点变动",
  `is_activated` int(11) NULL COMMENT "是否启用",
  `is_deactivated` int(11) NULL COMMENT "是否停用",
  `is_current` int(11) NULL COMMENT "是否当前生效区间",
  `is_leaf` int(11) NULL COMMENT "是否叶子部门",
  `creator` varchar(65533) NULL COMMENT "创建人",
  `updater` varchar(65533) NULL COMMENT "更新人",
  `create_time` datetime NULL COMMENT "创建时间",
  `update_time` datetime NULL COMMENT "更新时间"
);

CREATE TABLE `public_rqm_dwd_h` (
  `create_time` datetime NULL COMMENT "需求创建时间",
  `is_delete` bigint(20) NULL COMMENT "是否删除",
  `is_aborted` bigint(20) NULL COMMENT "是否终止",
  `creator` varchar(50) NULL COMMENT "需求创建人" COLLATE UTF8MB4_GENERAL_CI,
  `id` bigint(20) NULL COMMENT "ID",
  `date` datetime NULL COMMENT "分区",
  `rqm_id` bigint(20) NULL COMMENT "需求id",
  `unique_rqm_id` varchar(128) NULL COMMENT "需求主键ID {source}_{rqm_id}, 不提供single_source_rqm_id" COLLATE UTF8MB4_GENERAL_CI,
  `os` varchar(64) NULL COMMENT "端: iOS Android FE Server QA PM" COLLATE UTF8MB4_GENERAL_CI,
  `role_name` varchar(64) NULL COMMENT "角色名称: {role_type}_{os}" COLLATE UTF8MB4_GENERAL_CI,
  `member_name` varchar(64) NULL COMMENT "成员姓名邮箱前缀" COLLATE UTF8MB4_GENERAL_CI,
  `source` varchar(50) NULL COMMENT "需求来源: Rocket Meego Jira" COLLATE UTF8MB4_GENERAL_CI,
  `is_outer` bigint(20) NULL COMMENT "是否外部需求",
  `space_id` varchar(128) NULL COMMENT "需求所属空间ID" COLLATE UTF8MB4_GENERAL_CI,
  `space_name` varchar(100) NULL COMMENT "需求所属空间名称" COLLATE UTF8MB4_GENERAL_CI,
  `business_line` varchar(256) NULL COMMENT "业务线" COLLATE UTF8MB4_GENERAL_CI,
  `business_ids` varchar(512) NULL COMMENT "业务线ID,   id1/id2" COLLATE UTF8MB4_GENERAL_CI,
  `business_line_1` varchar(512) NULL COMMENT "一级业务线" COLLATE UTF8MB4_GENERAL_CI,
  `business_line_2` varchar(512) NULL COMMENT "二级业务线" COLLATE UTF8MB4_GENERAL_CI,
  `business_line_3` varchar(512) NULL COMMENT "三级业务线" COLLATE UTF8MB4_GENERAL_CI,
  `rqm_type` varchar(100) NULL COMMENT "需求类型" COLLATE UTF8MB4_GENERAL_CI,
  `rqm_name` varchar(200) NULL COMMENT "需求名称" COLLATE UTF8MB4_GENERAL_CI,
  `priority` varchar(10) NULL COMMENT "需求优先级" COLLATE UTF8MB4_GENERAL_CI,
  `rqm_status` varchar(64) NULL COMMENT "需求状态" COLLATE UTF8MB4_GENERAL_CI,
  `tag` varchar(100) NULL COMMENT "需求标签" COLLATE UTF8MB4_GENERAL_CI,
  `url` varchar(200) NULL COMMENT "需求链接" COLLATE UTF8MB4_GENERAL_CI,
  `plan_sprint` varchar(512) NULL COMMENT "规划迭代" COLLATE UTF8MB4_GENERAL_CI,
  `is_reverse` varchar(64) NULL COMMENT "是否倒排" COLLATE UTF8MB4_GENERAL_CI,
  `release_version` varchar(512) NULL COMMENT "发布版本" COLLATE UTF8MB4_GENERAL_CI,
  `plan_version` varchar(512) NULL COMMENT "规划版本" COLLATE UTF8MB4_GENERAL_CI,
  `end_time` datetime NULL COMMENT "流程完成时间",
  `rqm_review_time` datetime NULL COMMENT "需求评审时间",
  `tech_review_time` datetime NULL COMMENT "技术评审时间",
  `dev_start_time` datetime NULL COMMENT "研发开始时间",
  `dev_end_time` datetime NULL COMMENT "研发完成时间",
  `test_start_time` datetime NULL COMMENT "测试开始时间",
  `test_end_time` datetime NULL COMMENT "测试完成时间",
  `release_start_time` datetime NULL COMMENT "发布开始时间",
  `release_end_time` datetime NULL COMMENT "发布完成时间",
  `delivery_end_time` datetime NULL COMMENT "交付完成时间,口径是:if(test_end_time is ,if(release_end_time is ,end_time,release_end_time),test_end_time)",
  `product_duration` double NULL COMMENT "产品阶段时长",
  `plan_duration` double NULL COMMENT "研发排期时长",
  `dev_duration` double NULL COMMENT "研发阶段时长",
  `test_duration` double NULL COMMENT "测试阶段时长",
  `test_plan_duration` double NULL COMMENT "测试排期阶段时长",
  `release_duration` double NULL COMMENT "发布阶段时长",
  `verify_duration` double NULL COMMENT "验收阶段时长",
  `dev_wait_duration` double NULL COMMENT "开发等待时长",
  `test_wait_duration` double NULL COMMENT "测试等待时长",
  `release_wait_duration` double NULL COMMENT "发布等待时长",
  `rd_cycle_duration` double NULL COMMENT "研发周期时长",
  `full_cycle_duration` double NULL COMMENT "全周期时长",
  `os_release_version` varchar(256) NULL COMMENT "分端发布版本" COLLATE UTF8MB4_GENERAL_CI,
  `os_plan_version` varchar(256) NULL COMMENT "分端规划版本" COLLATE UTF8MB4_GENERAL_CI,
  `os_create_time` datetime NULL COMMENT "分端需求创建时间",
  `os_end_time` datetime NULL COMMENT "分端流程完成时间",
  `os_rqm_review_time` datetime NULL COMMENT "分端需求评审时间",
  `os_tech_review_time` datetime NULL COMMENT "分端技术评审时间",
  `os_dev_start_time` datetime NULL COMMENT "分端研发开始时间",
  `os_dev_end_time` datetime NULL COMMENT "分端研发完成时间",
  `os_test_start_time` datetime NULL COMMENT "分端测试开始时间",
  `os_test_end_time` datetime NULL COMMENT "分端测试完成时间",
  `os_release_start_time` datetime NULL COMMENT "分端发布开始时间",
  `os_release_end_time` datetime NULL COMMENT "分端发布完成时间",
  `os_product_duration` double NULL COMMENT "分端产品阶段时长",
  `os_plan_duration` double NULL COMMENT "分端研发排期时长",
  `os_dev_duration` double NULL COMMENT "分端研发阶段时长",
  `os_test_duration` double NULL COMMENT "分端测试阶段时长",
  `os_test_plan_duration` double NULL COMMENT "分端测试排期阶段时长",
  `os_release_duration` double NULL COMMENT "分端发布阶段时长",
  `os_verify_duration` double NULL COMMENT "分端验收阶段时长",
  `os_dev_wait_duration` double NULL COMMENT "分端开发等待时长",
  `os_test_wait_duration` double NULL COMMENT "分端测试等待时长",
  `os_release_wait_duration` double NULL COMMENT "分端发布等待时长",
  `os_rd_cycle_duration` double NULL COMMENT "分端研发周期时长",
  `os_full_cycle_duration` double NULL COMMENT "分端全周期时长",
  `role_type` varchar(64) NULL COMMENT "角色类型: RD QA PM UI/UX" COLLATE UTF8MB4_GENERAL_CI,
  `dept_full_path` varchar(100) NULL COMMENT "部门全名ID形式,包含父部门, E.G /L1_ID/L2_ID/L3_ID" COLLATE UTF8MB4_GENERAL_CI,
  `workload` double NULL COMMENT "工作量",
  `os_mem_plan_start_time` datetime NULL COMMENT "工作计划开始时间",
  `os_mem_plan_end_time` datetime NULL COMMENT "工作计划完成时间",
  `os_mem_actual_start_time` datetime NULL COMMENT "工作实际开始时间",
  `os_mem_actual_end_time` datetime NULL COMMENT "工作实际完成时间",
  `is_template` int(11) NULL COMMENT "是否配置模板映射接入",
  `legal_status` varchar(100) NULL COMMENT "合规评审状态" COLLATE UTF8MB4_GENERAL_CI,
  `legal_switch` varchar(32) NULL COMMENT "合规评审开关 0: 未配置 1: 关闭 2: 开启" COLLATE UTF8MB4_GENERAL_CI,
  `legal_url` varchar(200) NULL COMMENT "合规工单链接" COLLATE UTF8MB4_GENERAL_CI,
  `sdlc_status` varchar(100) NULL COMMENT "安全评审状态" COLLATE UTF8MB4_GENERAL_CI,
  `sdlc_switch` varchar(32) NULL COMMENT "安全评审开关 0: 未配置 1: 关闭 2: 开启" COLLATE UTF8MB4_GENERAL_CI,
  `sdlc_url` varchar(200) NULL COMMENT "安全工单链接" COLLATE UTF8MB4_GENERAL_CI,
  `test_method` varchar(128) NULL COMMENT "测试方式" COLLATE UTF8MB4_GENERAL_CI,
  `security_test` varchar(128) NULL COMMENT "安全测试开关" COLLATE UTF8MB4_GENERAL_CI,
  `un_sl_reason` varchar(128) NULL COMMENT "未左移需求原因" COLLATE UTF8MB4_GENERAL_CI,
  `case_generate_method` varchar(128) NULL COMMENT "自动化用例编写方式" COLLATE UTF8MB4_GENERAL_CI,
  `is_standard_requirement` varchar(128) NULL COMMENT "是否标准需求" COLLATE UTF8MB4_GENERAL_CI,
  `is_standard_release` varchar(128) NULL COMMENT "是否标准发布" COLLATE UTF8MB4_GENERAL_CI,
  `is_qa_intervene` varchar(128) NULL COMMENT "专项字段:QA是否人工介入" COLLATE UTF8MB4_GENERAL_CI,
  `rqm_category` varchar(128) NULL COMMENT "专项字段:需求类别" COLLATE UTF8MB4_GENERAL_CI,
  `milestone_1_time` datetime NULL COMMENT "第1里程碑时间",
  `milestone_2_time` datetime NULL COMMENT "第2号里程碑时间",
  `milestone_3_time` datetime NULL COMMENT "第3号里程碑时间",
  `milestone_4_time` datetime NULL COMMENT "第4号里程碑时间",
  `milestone_5_time` datetime NULL COMMENT "第5号里程碑时间",
  `milestone_6_time` datetime NULL COMMENT "第6号里程碑时间",
  `milestone_7_time` datetime NULL COMMENT "第7号里程碑时间",
  `milestone_8_time` datetime NULL COMMENT "第8号里程碑时间",
  `milestone_9_time` datetime NULL COMMENT "第9号里程碑时间",
  `milestone_10_time` datetime NULL COMMENT "第10号里程碑时间",
  `milestone_11_time` datetime NULL COMMENT "第11里程碑时间",
  `milestone_12_time` datetime NULL COMMENT "第12号里程碑时间",
  `milestone_13_time` datetime NULL COMMENT "第13号里程碑时间",
  `milestone_14_time` datetime NULL COMMENT "第14号里程碑时间",
  `milestone_15_time` datetime NULL COMMENT "第15号里程碑时间",
  `milestone_16_time` datetime NULL COMMENT "第16号里程碑时间",
  `milestone_17_time` datetime NULL COMMENT "第17号里程碑时间",
  `milestone_18_time` datetime NULL COMMENT "第18号里程碑时间",
  `milestone_19_time` datetime NULL COMMENT "第19号里程碑时间",
  `milestone_20_time` datetime NULL COMMENT "第20号里程碑时间",
  `milestone_21_time` datetime NULL COMMENT "第21号里程碑时间",
  `milestone_22_time` datetime NULL COMMENT "第22号里程碑时间",
  `milestone_23_time` datetime NULL COMMENT "第23号里程碑时间",
  `milestone_24_time` datetime NULL COMMENT "第24号里程碑时间",
  `milestone_25_time` datetime NULL COMMENT "第25号里程碑时间",
  `os_milestone_1_time` datetime NULL COMMENT "分端第1里程碑时间",
  `os_milestone_2_time` datetime NULL COMMENT "分端第2号里程碑时间",
  `os_milestone_3_time` datetime NULL COMMENT "分端第3号里程碑时间",
  `os_milestone_4_time` datetime NULL COMMENT "分端第4号里程碑时间",
  `os_milestone_5_time` datetime NULL COMMENT "分端第5号里程碑时间",
  `os_milestone_6_time` datetime NULL COMMENT "分端第6号里程碑时间",
  `os_milestone_7_time` datetime NULL COMMENT "分端第7号里程碑时间",
  `os_milestone_8_time` datetime NULL COMMENT "分端第8号里程碑时间",
  `os_milestone_9_time` datetime NULL COMMENT "分端第9号里程碑时间",
  `os_milestone_10_time` datetime NULL COMMENT "分端第10号里程碑时间",
  `os_milestone_11_time` datetime NULL COMMENT "分端第11里程碑时间",
  `os_milestone_12_time` datetime NULL COMMENT "分端第12号里程碑时间",
  `os_milestone_13_time` datetime NULL COMMENT "分端第13号里程碑时间",
  `os_milestone_14_time` datetime NULL COMMENT "分端第14号里程碑时间",
  `os_milestone_15_time` datetime NULL COMMENT "分端第15号里程碑时间",
  `os_milestone_16_time` datetime NULL COMMENT "分端第16号里程碑时间",
  `os_milestone_17_time` datetime NULL COMMENT "分端第17号里程碑时间",
  `os_milestone_18_time` datetime NULL COMMENT "分端第18号里程碑时间",
  `os_milestone_19_time` datetime NULL COMMENT "分端第19号里程碑时间",
  `os_milestone_20_time` datetime NULL COMMENT "分端第20号里程碑时间",
  `os_milestone_21_time` datetime NULL COMMENT "分端第21号里程碑时间",
  `os_milestone_22_time` datetime NULL COMMENT "分端第22号里程碑时间",
  `os_milestone_23_time` datetime NULL COMMENT "分端第23号里程碑时间",
  `os_milestone_24_time` datetime NULL COMMENT "分端第24号里程碑时间",
  `os_milestone_25_time` datetime NULL COMMENT "分端第25号里程碑时间",
  `custom_duration_1` double NULL COMMENT "自定义阶段时长1",
  `custom_duration_2` double NULL COMMENT "自定义阶段时长2",
  `custom_duration_3` double NULL COMMENT "自定义阶段时长3",
  `custom_duration_4` double NULL COMMENT "自定义阶段时长4",
  `custom_duration_5` double NULL COMMENT "自定义阶段时长5",
  `custom_duration_6` double NULL COMMENT "自定义阶段时长6",
  `custom_duration_7` double NULL COMMENT "自定义阶段时长7",
  `custom_duration_8` double NULL COMMENT "自定义阶段时长8",
  `custom_duration_9` double NULL COMMENT "自定义阶段时长9",
  `custom_duration_10` double NULL COMMENT "自定义阶段时长10",
  `custom_duration_11` double NULL COMMENT "自定义阶段时长11",
  `custom_duration_12` double NULL COMMENT "自定义阶段时长12",
  `custom_duration_13` double NULL COMMENT "自定义阶段时长13",
  `custom_duration_14` double NULL COMMENT "自定义阶段时长14",
  `custom_duration_15` double NULL COMMENT "自定义阶段时长15",
  `custom_duration_16` double NULL COMMENT "自定义阶段时长16",
  `custom_duration_17` double NULL COMMENT "自定义阶段时长17",
  `custom_duration_18` double NULL COMMENT "自定义阶段时长18",
  `custom_duration_19` double NULL COMMENT "自定义阶段时长19",
  `custom_duration_20` double NULL COMMENT "自定义阶段时长20",
  `self_define_1` varchar(65533) NULL COMMENT "自定义字段1" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_2` varchar(65533) NULL COMMENT "自定义字段2" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_3` varchar(65533) NULL COMMENT "自定义字段3" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_4` varchar(65533) NULL COMMENT "自定义字段4" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_5` varchar(65533) NULL COMMENT "自定义字段5" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_6` varchar(65533) NULL COMMENT "自定义字段6" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_7` varchar(65533) NULL COMMENT "自定义字段7" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_8` varchar(65533) NULL COMMENT "自定义字段8" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_9` varchar(65533) NULL COMMENT "自定义字段9" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_10` varchar(65533) NULL COMMENT "自定义字段10" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_11` varchar(65533) NULL COMMENT "自定义字段11" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_12` varchar(65533) NULL COMMENT "自定义字段12" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_13` varchar(65533) NULL COMMENT "自定义字段13" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_14` varchar(65533) NULL COMMENT "自定义字段14" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_15` varchar(65533) NULL COMMENT "自定义字段15" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_16` varchar(65533) NULL COMMENT "自定义字段16" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_17` varchar(65533) NULL COMMENT "自定义字段17" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_18` varchar(65533) NULL COMMENT "自定义字段18" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_19` varchar(65533) NULL COMMENT "自定义字段19" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_20` varchar(65533) NULL COMMENT "自定义字段20" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_21` varchar(65533) NULL COMMENT "自定义字段21" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_22` varchar(65533) NULL COMMENT "自定义字段22" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_23` varchar(65533) NULL COMMENT "自定义字段23" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_24` varchar(65533) NULL COMMENT "自定义字段24" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_25` varchar(65533) NULL COMMENT "自定义字段25" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_26` varchar(65533) NULL COMMENT "自定义字段26" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_27` varchar(65533) NULL COMMENT "自定义字段27" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_28` varchar(65533) NULL COMMENT "自定义字段28" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_29` varchar(65533) NULL COMMENT "自定义字段29" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_30` varchar(65533) NULL COMMENT "自定义字段30" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_31` varchar(65533) NULL COMMENT "自定义字段31" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_32` varchar(65533) NULL COMMENT "自定义字段32" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_33` varchar(65533) NULL COMMENT "自定义字段33" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_34` varchar(65533) NULL COMMENT "自定义字段34" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_35` varchar(65533) NULL COMMENT "自定义字段35" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_36` varchar(65533) NULL COMMENT "自定义字段36" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_37` varchar(65533) NULL COMMENT "自定义字段37" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_38` varchar(65533) NULL COMMENT "自定义字段38" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_39` varchar(65533) NULL COMMENT "自定义字段39" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_40` varchar(65533) NULL COMMENT "自定义字段40" COLLATE UTF8MB4_GENERAL_CI,
  `update_time` datetime NULL COMMENT "更新时间",
  `role_owners` json NULL COMMENT "角色owners",
  `os_custom_duration_1` double NULL COMMENT "和os相关自定义阶段时长1",
  `os_custom_duration_2` double NULL COMMENT "和os相关自定义阶段时长2",
  `os_custom_duration_3` double NULL COMMENT "和os相关自定义阶段时长3",
  `os_custom_duration_4` double NULL COMMENT "和os相关自定义阶段时长4",
  `os_custom_duration_5` double NULL COMMENT "和os相关自定义阶段时长5",
  `os_custom_duration_6` double NULL COMMENT "和os相关自定义阶段时长6",
  `os_custom_duration_7` double NULL COMMENT "和os相关自定义阶段时长7",
  `os_custom_duration_8` double NULL COMMENT "和os相关自定义阶段时长8",
  `os_custom_duration_9` double NULL COMMENT "和os相关自定义阶段时长9",
  `os_custom_duration_10` double NULL COMMENT "和os相关自定义阶段时长10",
  `os_custom_duration_11` double NULL COMMENT "和os相关自定义阶段时长11",
  `os_custom_duration_12` double NULL COMMENT "和os相关自定义阶段时长12",
  `os_custom_duration_13` double NULL COMMENT "和os相关自定义阶段时长13",
  `os_custom_duration_14` double NULL COMMENT "和os相关自定义阶段时长14",
  `os_custom_duration_15` double NULL COMMENT "和os相关自定义阶段时长15",
  `os_custom_duration_16` double NULL COMMENT "和os相关自定义阶段时长16",
  `os_custom_duration_17` double NULL COMMENT "和os相关自定义阶段时长17",
  `os_custom_duration_18` double NULL COMMENT "和os相关自定义阶段时长18",
  `os_custom_duration_19` double NULL COMMENT "和os相关自定义阶段时长19",
  `os_custom_duration_20` double NULL COMMENT "和os相关自定义阶段时长20",
  `mr_latest_merge_time` datetime NULL COMMENT "mr最后一次合入时间",
  `os_mr_latest_merge_time` datetime NULL COMMENT "分端mr最后一次合入时间",
  `member_name_deptindex_1` varchar(128) NULL COMMENT "member_name在需求完成时间的所属部门" COLLATE UTF8MB4_GENERAL_CI,
  `member_name_leaderindex_1` bigint(20) NULL COMMENT "memeber_name在需求完成时间所汇报的leader_id",
  `rqm_os_cnts` bigint(20) NULL COMMENT "参与研发端数",
  `rqm_workload` double NULL COMMENT "需求粒度工作量(不包含修Bug)",
  `rqm_dev_workload` double NULL COMMENT "需求粒度研发工作量",
  `rqm_test_workload` double NULL COMMENT "需求粒度测试工作量",
  `rqm_member_cnts` bigint(20) NULL COMMENT "需求研发人员数量",
  `rqm_test_member_cnts` bigint(20) NULL COMMENT "需求测试人员数量",
  `max_rqm_dev_workload` double NULL COMMENT "需求开发最大工作量",
  `max_rqm_test_workload` double NULL COMMENT "需求测试最大工作量",
  `self_define_41` varchar(65533) NULL COMMENT "自定义字段41" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_42` varchar(65533) NULL COMMENT "自定义字段42" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_43` varchar(65533) NULL COMMENT "自定义字段43" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_44` varchar(65533) NULL COMMENT "自定义字段44" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_45` varchar(65533) NULL COMMENT "自定义字段45" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_46` varchar(65533) NULL COMMENT "自定义字段46" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_47` varchar(65533) NULL COMMENT "自定义字段47" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_48` varchar(65533) NULL COMMENT "自定义字段48" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_49` varchar(65533) NULL COMMENT "自定义字段49" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_50` varchar(65533) NULL COMMENT "自定义字段50" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_51` varchar(65533) NULL COMMENT "自定义字段51" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_52` varchar(65533) NULL COMMENT "自定义字段52" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_53` varchar(65533) NULL COMMENT "自定义字段53" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_54` varchar(65533) NULL COMMENT "自定义字段54" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_55` varchar(65533) NULL COMMENT "自定义字段55" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_56` varchar(65533) NULL COMMENT "自定义字段56" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_57` varchar(65533) NULL COMMENT "自定义字段57" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_58` varchar(65533) NULL COMMENT "自定义字段58" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_59` varchar(65533) NULL COMMENT "自定义字段59" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_60` varchar(65533) NULL COMMENT "自定义字段60" COLLATE UTF8MB4_GENERAL_CI,
  `plan_count` bigint(20) NULL COMMENT "需求关联下计划数量",
  `minder_count` bigint(20) NULL COMMENT "需求下关联用例数量",
  `executed_minder_count` bigint(20) NULL COMMENT "需求下关联用例数量",
  `origin_meego_added_loc` bigint(20) NULL COMMENT "meego关联MR added_loc 聚合,原始值",
  `origin_meego_deleted_loc` bigint(20) NULL COMMENT "meego关联MR deleted_loc 聚合,原始值",
  `dev_latest_os` varchar(65533) NULL COMMENT "开发时间最晚完成端" COLLATE UTF8MB4_GENERAL_CI,
  `last_one_os_dev_end_time` datetime NULL COMMENT "最晚开发完成时间",
  `last_two_os_dev_end_time` datetime NULL COMMENT "次晚开发完成时间",
  `rqm_os` varchar(64) NULL COMMENT "需求端" COLLATE UTF8MB4_GENERAL_CI,
  `rqm_map_end` varchar(512) NULL COMMENT "端MR语言对应端" COLLATE UTF8MB4_GENERAL_CI,
  `mr_num` bigint(20) NULL COMMENT "需求绑定MR数量",
  `mr_detail` varchar(512) NULL COMMENT "change_id列表" COLLATE UTF8MB4_GENERAL_CI,
  `no_mr_bind` bigint(20) NULL COMMENT "需求本端是否绑定MR,1为是,0为否",
  `all_mr_bind` bigint(20) NULL COMMENT "需求是否绑定MR,1为是,0为否",
  `node_name` varchar(64) NULL COMMENT "节点名称" COLLATE UTF8MB4_GENERAL_CI,
  `bind_mr_list` varchar(128) NULL COMMENT "需求绑定MR列表" COLLATE UTF8MB4_GENERAL_CI,
  `minder_system_count` bigint(20) NULL COMMENT "测试用例数*系统类型数",
  `executed_minder_system_count` bigint(20) NULL COMMENT "执行测试用例数*系统类型数",
  `rqm_include_dev_workload` double NULL COMMENT "需求粒度研发工作量:开发,技术方案设计,联调,研发自测,技术评审,showcase,CodeReview,上线",
  `rqm_include_test_workload` double NULL COMMENT "需求粒度测试工作量:测试,测试用例,冒烟测试,RD自测后QA验收, 集成测试",
  `self_define_61` varchar(65533) NULL COMMENT "自定义字段61" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_62` varchar(65533) NULL COMMENT "自定义字段62" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_63` varchar(65533) NULL COMMENT "自定义字段63" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_64` varchar(65533) NULL COMMENT "自定义字段64" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_65` varchar(65533) NULL COMMENT "自定义字段65" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_66` varchar(65533) NULL COMMENT "自定义字段66" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_67` varchar(65533) NULL COMMENT "自定义字段67" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_68` varchar(65533) NULL COMMENT "自定义字段68" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_69` varchar(65533) NULL COMMENT "自定义字段69" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_70` varchar(65533) NULL COMMENT "自定义字段70" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_71` varchar(65533) NULL COMMENT "自定义字段71" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_72` varchar(65533) NULL COMMENT "自定义字段72" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_73` varchar(65533) NULL COMMENT "自定义字段73" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_74` varchar(65533) NULL COMMENT "自定义字段74" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_75` varchar(65533) NULL COMMENT "自定义字段75" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_76` varchar(65533) NULL COMMENT "自定义字段76" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_77` varchar(65533) NULL COMMENT "自定义字段77" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_78` varchar(65533) NULL COMMENT "自定义字段78" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_79` varchar(65533) NULL COMMENT "自定义字段79" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_80` varchar(65533) NULL COMMENT "自定义字段80" COLLATE UTF8MB4_GENERAL_CI,
  `bytest_exec_cnt` bigint(20) NULL COMMENT "bytest测试用例执行数",
  `bytest_exec_succ_cnt` bigint(20) NULL COMMENT "bytest测试用例执行成功数",
  `bytest_plan_cnt` bigint(20) NULL COMMENT "bytest测试用例计划执行数",
  `bytest_info` varchar(65533) NULL COMMENT "绑定bytest执行详情" COLLATE UTF8MB4_GENERAL_CI,
  `mr_cnt` bigint(20) NULL COMMENT "关联MR数",
  `code_bug_cnt` bigint(20) NULL COMMENT "代码归因有效缺陷数",
  `self_define_81` varchar(65533) NULL COMMENT "自定义字段81" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_82` varchar(65533) NULL COMMENT "自定义字段82" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_83` varchar(65533) NULL COMMENT "自定义字段83" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_84` varchar(65533) NULL COMMENT "自定义字段84" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_85` varchar(65533) NULL COMMENT "自定义字段85" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_86` varchar(65533) NULL COMMENT "自定义字段86" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_87` varchar(65533) NULL COMMENT "自定义字段87" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_88` varchar(65533) NULL COMMENT "自定义字段88" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_89` varchar(65533) NULL COMMENT "自定义字段89" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_90` varchar(65533) NULL COMMENT "自定义字段90" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_91` varchar(65533) NULL COMMENT "自定义字段91" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_92` varchar(65533) NULL COMMENT "自定义字段92" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_93` varchar(65533) NULL COMMENT "自定义字段93" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_94` varchar(65533) NULL COMMENT "自定义字段94" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_95` varchar(65533) NULL COMMENT "自定义字段95" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_96` varchar(65533) NULL COMMENT "自定义字段96" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_97` varchar(65533) NULL COMMENT "自定义字段97" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_98` varchar(65533) NULL COMMENT "自定义字段98" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_99` varchar(65533) NULL COMMENT "自定义字段99" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_100` varchar(65533) NULL COMMENT "自定义字段100" COLLATE UTF8MB4_GENERAL_CI,
  `bc_dev_start_time` varchar(512) NULL COMMENT "bc_dev_start_time" COLLATE UTF8MB4_GENERAL_CI,
  `bc_dev_end_time` varchar(512) NULL COMMENT "bc_dev_end_time" COLLATE UTF8MB4_GENERAL_CI,
  `bc_test_in_time` varchar(512) NULL COMMENT "bc_test_in_time" COLLATE UTF8MB4_GENERAL_CI,
  `bc_finish_time` varchar(512) NULL COMMENT "bc_finish_time" COLLATE UTF8MB4_GENERAL_CI,
  `bc_first_commit_time` varchar(512) NULL COMMENT "bc_first_commit_time" COLLATE UTF8MB4_GENERAL_CI,
  `bc_bits_first_commit_time` varchar(512) NULL COMMENT "bc_bits_first_commit_time" COLLATE UTF8MB4_GENERAL_CI,
  `before_avg_workload` varchar(512) NULL COMMENT "before_avg_workload" COLLATE UTF8MB4_GENERAL_CI,
  `is_bind_signal` varchar(512) NULL COMMENT "is_bind_signal" COLLATE UTF8MB4_GENERAL_CI,
  `transition_detail` varchar(512) NULL COMMENT "transition_detail" COLLATE UTF8MB4_GENERAL_CI,
  `is_signal_abnormal` varchar(512) NULL COMMENT "is_signal_abnormal" COLLATE UTF8MB4_GENERAL_CI,
  `whiltelist_flag` varchar(32) NULL COMMENT "whiltelist_flag" COLLATE UTF8MB4_GENERAL_CI,
  `milestone_26_time` datetime NULL COMMENT "第26里程碑时间",
  `milestone_27_time` datetime NULL COMMENT "第27里程碑时间",
  `milestone_28_time` datetime NULL COMMENT "第28里程碑时间",
  `milestone_29_time` datetime NULL COMMENT "第29里程碑时间",
  `milestone_30_time` datetime NULL COMMENT "第30里程碑时间",
  `milestone_31_time` datetime NULL COMMENT "第31里程碑时间",
  `milestone_32_time` datetime NULL COMMENT "第32里程碑时间",
  `milestone_33_time` datetime NULL COMMENT "第33里程碑时间",
  `milestone_34_time` datetime NULL COMMENT "第34里程碑时间",
  `milestone_35_time` datetime NULL COMMENT "第35里程碑时间",
  `milestone_36_time` datetime NULL COMMENT "第36里程碑时间",
  `milestone_37_time` datetime NULL COMMENT "第37里程碑时间",
  `milestone_38_time` datetime NULL COMMENT "第38里程碑时间",
  `milestone_39_time` datetime NULL COMMENT "第39里程碑时间",
  `milestone_40_time` datetime NULL COMMENT "第40里程碑时间",
  `milestone_41_time` datetime NULL COMMENT "第41里程碑时间",
  `milestone_42_time` datetime NULL COMMENT "第42里程碑时间",
  `milestone_43_time` datetime NULL COMMENT "第43里程碑时间",
  `milestone_44_time` datetime NULL COMMENT "第44里程碑时间",
  `milestone_45_time` datetime NULL COMMENT "第45里程碑时间",
  `milestone_46_time` datetime NULL COMMENT "第46里程碑时间",
  `milestone_47_time` datetime NULL COMMENT "第47里程碑时间",
  `milestone_48_time` datetime NULL COMMENT "第48里程碑时间",
  `milestone_49_time` datetime NULL COMMENT "第49里程碑时间",
  `milestone_50_time` datetime NULL COMMENT "第50里程碑时间",
  `os_milestone_26_time` datetime NULL COMMENT "分端第26里程碑时间",
  `os_milestone_27_time` datetime NULL COMMENT "分端第27里程碑时间",
  `os_milestone_28_time` datetime NULL COMMENT "分端第28里程碑时间",
  `os_milestone_29_time` datetime NULL COMMENT "分端第29里程碑时间",
  `os_milestone_30_time` datetime NULL COMMENT "分端第30里程碑时间",
  `os_milestone_31_time` datetime NULL COMMENT "分端第31里程碑时间",
  `os_milestone_32_time` datetime NULL COMMENT "分端第32里程碑时间",
  `os_milestone_33_time` datetime NULL COMMENT "分端第33里程碑时间",
  `os_milestone_34_time` datetime NULL COMMENT "分端第34里程碑时间",
  `os_milestone_35_time` datetime NULL COMMENT "分端第35里程碑时间",
  `os_milestone_36_time` datetime NULL COMMENT "分端第36里程碑时间",
  `os_milestone_37_time` datetime NULL COMMENT "分端第37里程碑时间",
  `os_milestone_38_time` datetime NULL COMMENT "分端第38里程碑时间",
  `os_milestone_39_time` datetime NULL COMMENT "分端第39里程碑时间",
  `os_milestone_40_time` datetime NULL COMMENT "分端第40里程碑时间",
  `os_milestone_41_time` datetime NULL COMMENT "分端第41里程碑时间",
  `os_milestone_42_time` datetime NULL COMMENT "分端第42里程碑时间",
  `os_milestone_43_time` datetime NULL COMMENT "分端第43里程碑时间",
  `os_milestone_44_time` datetime NULL COMMENT "分端第44里程碑时间",
  `os_milestone_45_time` datetime NULL COMMENT "分端第45里程碑时间",
  `os_milestone_46_time` datetime NULL COMMENT "分端第46里程碑时间",
  `os_milestone_47_time` datetime NULL COMMENT "分端第47里程碑时间",
  `os_milestone_48_time` datetime NULL COMMENT "分端第48里程碑时间",
  `os_milestone_49_time` datetime NULL COMMENT "分端第49里程碑时间",
  `os_milestone_50_time` datetime NULL COMMENT "分端第50里程碑时间",
  `custom_duration_21` double NULL COMMENT "自定义阶段时长21",
  `custom_duration_22` double NULL COMMENT "自定义阶段时长22",
  `custom_duration_23` double NULL COMMENT "自定义阶段时长23",
  `custom_duration_24` double NULL COMMENT "自定义阶段时长24",
  `custom_duration_25` double NULL COMMENT "自定义阶段时长25",
  `custom_duration_26` double NULL COMMENT "自定义阶段时长26",
  `custom_duration_27` double NULL COMMENT "自定义阶段时长27",
  `custom_duration_28` double NULL COMMENT "自定义阶段时长28",
  `custom_duration_29` double NULL COMMENT "自定义阶段时长29",
  `custom_duration_30` double NULL COMMENT "自定义阶段时长30",
  `os_custom_duration_21` double NULL COMMENT "分端自定义阶段时长21",
  `os_custom_duration_22` double NULL COMMENT "分端自定义阶段时长22",
  `os_custom_duration_23` double NULL COMMENT "分端自定义阶段时长23",
  `os_custom_duration_24` double NULL COMMENT "分端自定义阶段时长24",
  `os_custom_duration_25` double NULL COMMENT "分端自定义阶段时长25",
  `os_custom_duration_26` double NULL COMMENT "分端自定义阶段时长26",
  `os_custom_duration_27` double NULL COMMENT "分端自定义阶段时长27",
  `os_custom_duration_28` double NULL COMMENT "分端自定义阶段时长28",
  `os_custom_duration_29` double NULL COMMENT "分端自定义阶段时长29",
  `os_custom_duration_30` double NULL COMMENT "分端自定义阶段时长30",
  `qa_before_avg_workload` int(11) NULL COMMENT "qa_before_avg_workload",
  `rd_before_avg_workload` int(11) NULL COMMENT "rd_before_avg_workload",
  `aweme_bind_case_cnt` bigint(20) NULL COMMENT "aweme_bind_case_cnt",
  `people_scrum_list` json NULL COMMENT "people_scrum_list",
  `self_define_84_history` varchar(65533) NULL COMMENT "self_define_84_history" COLLATE UTF8MB4_GENERAL_CI,
  `cj_loc_json` json NULL COMMENT "cj_loc_json",
  `creator_dept_full_name` varchar(65533) NULL COMMENT "creator_dept_full_name" COLLATE UTF8MB4_GENERAL_CI,
  `creator_city` varchar(65533) NULL COMMENT "creator_city" COLLATE UTF8MB4_GENERAL_CI,
  `creator_country` varchar(65533) NULL COMMENT "creator_country" COLLATE UTF8MB4_GENERAL_CI,
  `creator_entry_time` datetime NULL COMMENT "creator_entry_time",
  `creator_employee_type` varchar(65533) NULL COMMENT "creator_employee_type" COLLATE UTF8MB4_GENERAL_CI,
  `creator_join_time` datetime NULL COMMENT "creator_join_time",
  `creator_sequence` varchar(65533) NULL COMMENT "creator_sequence" COLLATE UTF8MB4_GENERAL_CI,
  `member_dept_full_name` varchar(65533) NULL COMMENT "member_dept_full_name" COLLATE UTF8MB4_GENERAL_CI,
  `member_city` varchar(65533) NULL COMMENT "member_city" COLLATE UTF8MB4_GENERAL_CI,
  `member_country` varchar(65533) NULL COMMENT "member_country" COLLATE UTF8MB4_GENERAL_CI,
  `member_entry_time` datetime NULL COMMENT "member_entry_time",
  `member_employee_type` varchar(65533) NULL COMMENT "member_employee_type" COLLATE UTF8MB4_GENERAL_CI,
  `member_join_time` datetime NULL COMMENT "member_join_time",
  `member_is_leader` bigint(20) NULL COMMENT "member_is_leader",
  `member_leader_name` varchar(65533) NULL COMMENT "member_leader_name" COLLATE UTF8MB4_GENERAL_CI,
  `creator_is_leader` bigint(20) NULL COMMENT "需求创建人是否是leader",
  `creator_leader_name` varchar(65533) NULL COMMENT "需求创建人leader" COLLATE UTF8MB4_GENERAL_CI,
  `pre_aggr_field` json NULL COMMENT "预聚合字段",
  `rqm_bug_commit_loc` bigint(20) NULL COMMENT "rqm_bug_commit_loc",
  `product_mapping_json` json NULL COMMENT "product_mapping_json",
  `product_mapping_str` varchar(65533) NULL COMMENT "product_mapping_str" COLLATE UTF8MB4_GENERAL_CI,
  `member_sequence` varchar(65533) NULL COMMENT "member_sequence" COLLATE UTF8MB4_GENERAL_CI,
  `rqm_plan_end_time` datetime NULL COMMENT "需求分析计划完成时间",
  `os_rqm_plan_end_time` datetime NULL COMMENT "分端需求分析计划完成时间",
  `rqm_actual_end_time` datetime NULL COMMENT "需求分析实际完成时间",
  `os_rqm_actual_end_time` datetime NULL COMMENT "分端需求分析实际完成时间",
  `dev_plan_end_time` datetime NULL COMMENT "研发计划完成时间",
  `os_dev_plan_end_time` datetime NULL COMMENT "分端研发计划完成时间",
  `dev_actual_end_time` datetime NULL COMMENT "研发实际完成时间",
  `os_dev_actual_end_time` datetime NULL COMMENT "分端研发实际完成时间",
  `test_plan_end_time` datetime NULL COMMENT "测试计划完成时间",
  `os_test_plan_end_time` datetime NULL COMMENT "分端测试计划完成时间",
  `test_actual_end_time` datetime NULL COMMENT "测试实际完成时间",
  `os_test_actual_end_time` datetime NULL COMMENT "分端测试实际完成时间",
  `release_plan_end_time` datetime NULL COMMENT "发布计划完成时间",
  `os_release_plan_end_time` datetime NULL COMMENT "分端发布计划完成时间",
  `release_actual_end_time` datetime NULL COMMENT "发布实际完成时间",
  `os_release_actual_end_time` datetime NULL COMMENT "分端发布实际完成时间",
  `rqm_delay_duration` double NULL COMMENT "需求分析延期时长",
  `os_rqm_delay_duration` double NULL COMMENT "分端需求分析延期时长",
  `dev_delay_duration` double NULL COMMENT "研发延期时长",
  `os_dev_delay_duration` double NULL COMMENT "分端研发延期时长",
  `test_delay_duration` double NULL COMMENT "测试延期时长",
  `os_test_delay_duration` double NULL COMMENT "分端测试延期时长",
  `full_cycle_delay_duration` double NULL COMMENT "需求交付延期时长",
  `os_full_cycle_delay_duration` double NULL COMMENT "需求交付延期时长",
  `rqm_dev_role_workload` double NULL COMMENT "rqm_dev_role_workload",
  `rqm_test_role_workload` double NULL COMMENT "rqm_test_role_workload",
  `rqm_dev_test_workload_ratio` double NULL COMMENT "rqm_dev_test_workload_ratio",
  `rqm_test_role_cnt` bigint(20) NULL COMMENT "rqm_test_role_cnt",
  `rqm_dev_role_cnt` bigint(20) NULL COMMENT "rqm_dev_role_cnt",
  `rqm_min_test_actual_start_time` datetime NULL COMMENT "需求最小测试实际完成时间",
  `rqm_max_dev_actual_start_time` datetime NULL COMMENT "需求最大开发实际完成时间",
  `rqm_max_dev_plan_start_time` datetime NULL COMMENT "需求最大开发计划完成时间",
  `rqm_qa_cnt` bigint(20) NULL COMMENT "质量保障数据条数",
  `rqm_not_qa_cnt` bigint(20) NULL COMMENT "非质量保障数据条数",
  `signal_dev_end_time` datetime NULL COMMENT "signal_dev_end_time",
  `signal_test_end_time` datetime NULL COMMENT "signal_test_end_time",
  `signal_release_end_time` datetime NULL COMMENT "signal_release_end_time",
  `bc_period_json` json NULL COMMENT "bc_period_json",
  `lba_exceptional_changes` bigint(20) NULL DEFAULT NULL COMMENT "lba异常变更次数",
  `self_define_101` varchar(65533) NULL DEFAULT NULL COMMENT "自定义字段101" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_102` varchar(65533) NULL DEFAULT NULL COMMENT "自定义字段102" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_103` varchar(65533) NULL DEFAULT NULL COMMENT "自定义字段103" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_104` varchar(65533) NULL DEFAULT NULL COMMENT "自定义字段104" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_105` varchar(65533) NULL DEFAULT NULL COMMENT "自定义字段105" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_106` varchar(65533) NULL DEFAULT NULL COMMENT "自定义字段106" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_107` varchar(65533) NULL DEFAULT NULL COMMENT "自定义字段107" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_108` varchar(65533) NULL DEFAULT NULL COMMENT "自定义字段108" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_109` varchar(65533) NULL DEFAULT NULL COMMENT "自定义字段109" COLLATE UTF8MB4_GENERAL_CI,
  `self_define_110` varchar(65533) NULL DEFAULT NULL COMMENT "自定义字段110" COLLATE UTF8MB4_GENERAL_CI,
  `current_info` varchar(65533) NULL DEFAULT NULL COMMENT "进行中节点人员信息" COLLATE UTF8MB4_GENERAL_CI,
  `current_member` varchar(65533) NULL DEFAULT NULL COMMENT "进行中节点人员" COLLATE UTF8MB4_GENERAL_CI,
  `bits_workspace_names` varchar(512) NULL DEFAULT NULL COMMENT "需求关联的开发任务所在的Bits空间列表" COLLATE UTF8MB4_GENERAL_CI,
  `member_create_report_full_path` varchar(65533) NULL DEFAULT NULL COMMENT "" COLLATE UTF8MB4_GENERAL_CI,
  `member_actual_start_report_full_path` varchar(65533) NULL DEFAULT NULL COMMENT "" COLLATE UTF8MB4_GENERAL_CI,
  `member_release_end_report_full_path` varchar(65533) NULL DEFAULT NULL COMMENT "" COLLATE UTF8MB4_GENERAL_CI,
  `creator_create_report_full_path` varchar(65533) NULL DEFAULT NULL COMMENT "" COLLATE UTF8MB4_GENERAL_CI,
  `member_test_end_report_full_path` varchar(65533) NULL DEFAULT NULL COMMENT "" COLLATE UTF8MB4_GENERAL_CI,
  `member_test_start_report_full_path` varchar(65533) NULL DEFAULT NULL COMMENT "" COLLATE UTF8MB4_GENERAL_CI
);

CREATE TABLE `public_workitem_dwd_h_read` (
  `space_id` varchar(128) NULL COMMENT "工作项所属空间ID" COLLATE UTF8MB4_GENERAL_CI,
  `workitem_id` bigint(20) NULL COMMENT "工作项ID",
  `type_key` varchar(128) NULL COMMENT "工作项类型Key" COLLATE UTF8MB4_GENERAL_CI,
  `split_owner` varchar(64) NULL COMMENT "拆分人员" COLLATE UTF8MB4_GENERAL_CI,
  `id` bigint(20) NULL COMMENT "主键自增ID",
  `date` datetime NULL COMMENT "分区",
  `space_name` varchar(100) NULL COMMENT "工作项所属空间名称" COLLATE UTF8MB4_GENERAL_CI,
  `type_name` varchar(128) NULL COMMENT "工作项类型名称" COLLATE UTF8MB4_GENERAL_CI,
  `workitem_name` varchar(500) NULL COMMENT "工作项标题" COLLATE UTF8MB4_GENERAL_CI,
  `priority` varchar(32) NULL COMMENT "优先级" COLLATE UTF8MB4_GENERAL_CI,
  `status` varchar(32) NULL COMMENT "状态" COLLATE UTF8MB4_GENERAL_CI,
  `start_time` datetime NULL COMMENT "工作项创建时间",
  `owner` varchar(64) NULL COMMENT "创建人" COLLATE UTF8MB4_GENERAL_CI,
  `watchers` varchar(256) NULL COMMENT "关注人" COLLATE UTF8MB4_GENERAL_CI,
  `description` varchar(64) NULL COMMENT "描述" COLLATE UTF8MB4_GENERAL_CI,
  `business` varchar(64) NULL COMMENT "业务线" COLLATE UTF8MB4_GENERAL_CI,
  `current_status_operator` varchar(256) NULL COMMENT "当前负责人" COLLATE UTF8MB4_GENERAL_CI,
  `archiving_date` varchar(64) NULL COMMENT "归档日期" COLLATE UTF8MB4_GENERAL_CI,
  `archiving_status` varchar(64) NULL COMMENT "是否归档" COLLATE UTF8MB4_GENERAL_CI,
  `workitem_url` varchar(200) NULL COMMENT "Workitem链接" COLLATE UTF8MB4_GENERAL_CI,
  `role_owners` json NULL COMMENT "工作项人员信息",
  `special_1` varchar(512) NULL COMMENT "专项字段1" COLLATE UTF8MB4_GENERAL_CI,
  `special_2` varchar(512) NULL COMMENT "专项字段2" COLLATE UTF8MB4_GENERAL_CI,
  `special_3` varchar(512) NULL COMMENT "专项字段3" COLLATE UTF8MB4_GENERAL_CI,
  `special_4` varchar(512) NULL COMMENT "专项字段4" COLLATE UTF8MB4_GENERAL_CI,
  `special_5` varchar(512) NULL COMMENT "专项字段5" COLLATE UTF8MB4_GENERAL_CI,
  `special_6` varchar(512) NULL COMMENT "专项字段6" COLLATE UTF8MB4_GENERAL_CI,
  `special_7` varchar(512) NULL COMMENT "专项字段7" COLLATE UTF8MB4_GENERAL_CI,
  `special_8` varchar(512) NULL COMMENT "专项字段8" COLLATE UTF8MB4_GENERAL_CI,
  `special_9` varchar(512) NULL COMMENT "专项字段9" COLLATE UTF8MB4_GENERAL_CI,
  `special_10` varchar(512) NULL COMMENT "专项字段10" COLLATE UTF8MB4_GENERAL_CI,
  `ext1` varchar(65533) NULL COMMENT "自定义字段1" COLLATE UTF8MB4_GENERAL_CI,
  `ext2` varchar(65533) NULL COMMENT "自定义字段2" COLLATE UTF8MB4_GENERAL_CI,
  `ext3` varchar(65533) NULL COMMENT "自定义字段3" COLLATE UTF8MB4_GENERAL_CI,
  `ext4` varchar(65533) NULL COMMENT "自定义字段4" COLLATE UTF8MB4_GENERAL_CI,
  `ext5` varchar(65533) NULL COMMENT "自定义字段5" COLLATE UTF8MB4_GENERAL_CI,
  `ext6` varchar(65533) NULL COMMENT "自定义字段6" COLLATE UTF8MB4_GENERAL_CI,
  `ext7` varchar(65533) NULL COMMENT "自定义字段7" COLLATE UTF8MB4_GENERAL_CI,
  `ext8` varchar(65533) NULL COMMENT "自定义字段8" COLLATE UTF8MB4_GENERAL_CI,
  `ext9` varchar(65533) NULL COMMENT "自定义字段9" COLLATE UTF8MB4_GENERAL_CI,
  `ext10` varchar(65533) NULL COMMENT "自定义字段10" COLLATE UTF8MB4_GENERAL_CI,
  `ext11` varchar(65533) NULL COMMENT "自定义字段11" COLLATE UTF8MB4_GENERAL_CI,
  `ext12` varchar(65533) NULL COMMENT "自定义字段12" COLLATE UTF8MB4_GENERAL_CI,
  `ext13` varchar(65533) NULL COMMENT "自定义字段13" COLLATE UTF8MB4_GENERAL_CI,
  `ext14` varchar(65533) NULL COMMENT "自定义字段14" COLLATE UTF8MB4_GENERAL_CI,
  `ext15` varchar(65533) NULL COMMENT "自定义字段15" COLLATE UTF8MB4_GENERAL_CI,
  `ext16` varchar(65533) NULL COMMENT "自定义字段16" COLLATE UTF8MB4_GENERAL_CI,
  `ext17` varchar(65533) NULL COMMENT "自定义字段17" COLLATE UTF8MB4_GENERAL_CI,
  `ext18` varchar(65533) NULL COMMENT "自定义字段18" COLLATE UTF8MB4_GENERAL_CI,
  `ext19` varchar(65533) NULL COMMENT "自定义字段19" COLLATE UTF8MB4_GENERAL_CI,
  `ext20` varchar(65533) NULL COMMENT "自定义字段20" COLLATE UTF8MB4_GENERAL_CI,
  `ext21` varchar(65533) NULL COMMENT "自定义字段21" COLLATE UTF8MB4_GENERAL_CI,
  `ext22` varchar(65533) NULL COMMENT "自定义字段22" COLLATE UTF8MB4_GENERAL_CI,
  `ext23` varchar(65533) NULL COMMENT "自定义字段23" COLLATE UTF8MB4_GENERAL_CI,
  `ext24` varchar(65533) NULL COMMENT "自定义字段24" COLLATE UTF8MB4_GENERAL_CI,
  `ext25` varchar(65533) NULL COMMENT "自定义字段25" COLLATE UTF8MB4_GENERAL_CI,
  `ext26` varchar(65533) NULL COMMENT "自定义字段26" COLLATE UTF8MB4_GENERAL_CI,
  `ext27` varchar(65533) NULL COMMENT "自定义字段27" COLLATE UTF8MB4_GENERAL_CI,
  `ext28` varchar(65533) NULL COMMENT "自定义字段28" COLLATE UTF8MB4_GENERAL_CI,
  `ext29` varchar(65533) NULL COMMENT "自定义字段29" COLLATE UTF8MB4_GENERAL_CI,
  `ext30` varchar(65533) NULL COMMENT "自定义字段30" COLLATE UTF8MB4_GENERAL_CI,
  `ext31` varchar(65533) NULL COMMENT "自定义字段31" COLLATE UTF8MB4_GENERAL_CI,
  `ext32` varchar(65533) NULL COMMENT "自定义字段32" COLLATE UTF8MB4_GENERAL_CI,
  `ext33` varchar(65533) NULL COMMENT "自定义字段33" COLLATE UTF8MB4_GENERAL_CI,
  `ext34` varchar(65533) NULL COMMENT "自定义字段34" COLLATE UTF8MB4_GENERAL_CI,
  `ext35` varchar(65533) NULL COMMENT "自定义字段35" COLLATE UTF8MB4_GENERAL_CI,
  `ext36` varchar(65533) NULL COMMENT "自定义字段36" COLLATE UTF8MB4_GENERAL_CI,
  `ext37` varchar(65533) NULL COMMENT "自定义字段37" COLLATE UTF8MB4_GENERAL_CI,
  `ext38` varchar(65533) NULL COMMENT "自定义字段38" COLLATE UTF8MB4_GENERAL_CI,
  `ext39` varchar(65533) NULL COMMENT "自定义字段39" COLLATE UTF8MB4_GENERAL_CI,
  `ext40` varchar(65533) NULL COMMENT "自定义字段40" COLLATE UTF8MB4_GENERAL_CI,
  `ext41` varchar(65533) NULL COMMENT "自定义字段41" COLLATE UTF8MB4_GENERAL_CI,
  `ext42` varchar(65533) NULL COMMENT "自定义字段42" COLLATE UTF8MB4_GENERAL_CI,
  `ext43` varchar(65533) NULL COMMENT "自定义字段43" COLLATE UTF8MB4_GENERAL_CI,
  `ext44` varchar(65533) NULL COMMENT "自定义字段44" COLLATE UTF8MB4_GENERAL_CI,
  `ext45` varchar(65533) NULL COMMENT "自定义字段45" COLLATE UTF8MB4_GENERAL_CI,
  `ext46` varchar(65533) NULL COMMENT "自定义字段46" COLLATE UTF8MB4_GENERAL_CI,
  `ext47` varchar(65533) NULL COMMENT "自定义字段47" COLLATE UTF8MB4_GENERAL_CI,
  `ext48` varchar(65533) NULL COMMENT "自定义字段48" COLLATE UTF8MB4_GENERAL_CI,
  `ext49` varchar(65533) NULL COMMENT "自定义字段49" COLLATE UTF8MB4_GENERAL_CI,
  `ext50` varchar(65533) NULL COMMENT "自定义字段50" COLLATE UTF8MB4_GENERAL_CI,
  `ext51` varchar(65533) NULL COMMENT "自定义字段51" COLLATE UTF8MB4_GENERAL_CI,
  `ext52` varchar(65533) NULL COMMENT "自定义字段52" COLLATE UTF8MB4_GENERAL_CI,
  `ext53` varchar(65533) NULL COMMENT "自定义字段53" COLLATE UTF8MB4_GENERAL_CI,
  `ext54` varchar(65533) NULL COMMENT "自定义字段54" COLLATE UTF8MB4_GENERAL_CI,
  `ext55` varchar(65533) NULL COMMENT "自定义字段55" COLLATE UTF8MB4_GENERAL_CI,
  `ext56` varchar(65533) NULL COMMENT "自定义字段56" COLLATE UTF8MB4_GENERAL_CI,
  `ext57` varchar(65533) NULL COMMENT "自定义字段57" COLLATE UTF8MB4_GENERAL_CI,
  `ext58` varchar(65533) NULL COMMENT "自定义字段58" COLLATE UTF8MB4_GENERAL_CI,
  `ext59` varchar(65533) NULL COMMENT "自定义字段59" COLLATE UTF8MB4_GENERAL_CI,
  `ext60` varchar(65533) NULL COMMENT "自定义字段60" COLLATE UTF8MB4_GENERAL_CI,
  `update_time` datetime NULL COMMENT "更新时间",
  `workitem_data_count` bigint(20) NULL COMMENT "该工作项拆分后的数据条数",
  `rqm_name` varchar(64) NULL COMMENT "需求名称" COLLATE UTF8MB4_GENERAL_CI,
  `last_workday` varchar(128) NULL COMMENT "归档日期前的最后工作日" COLLATE UTF8MB4_GENERAL_CI
);