tab2id = {
    "nation": 0,
    "region": 1,
    "part": 2,
    "supplier": 3,
    "partsupp": 4,
    "customer": 5,
    "orders": 6,
    "lineitem": 7
}

tab2size = {
    "0": 25,
    "1": 5,
    "2": 200000,
    "3": 10000,
    "4": 800000,
    "5": 150000,
    "6": 1500000,
    "7": 6000000
}

col2id = {
    "nation.n_nationkey": 0,
    "nation.n_name": 1,
    "nation.n_regionkey": 2,
    "nation.n_comment": 3,
    "region.r_regionkey": 4,
    "region.r_name": 5,
    "region.r_comment": 6,
    "part.p_partkey": 7,
    "part.p_name": 8,
    "part.p_mfgr": 9,
    "part.p_brand": 10,
    "part.p_type": 11,
    "part.p_size": 12,
    "part.p_container": 13,
    "part.p_retailprice": 14,
    "part.p_comment": 15,
    "supplier.s_suppkey": 16,
    "supplier.s_name": 17,
    "supplier.s_address": 18,
    "supplier.s_nationkey": 19,
    "supplier.s_phone": 20,
    "supplier.s_acctbal": 21,
    "supplier.s_comment": 22,
    "partsupp.ps_partkey": 23,
    "partsupp.ps_suppkey": 24,
    "partsupp.ps_availqty": 25,
    "partsupp.ps_supplycost": 26,
    "partsupp.ps_comment": 27,
    "customer.c_custkey": 28,
    "customer.c_name": 29,
    "customer.c_address": 30,
    "customer.c_nationkey": 31,
    "customer.c_phone": 32,
    "customer.c_acctbal": 33,
    "customer.c_mktsegment": 34,
    "customer.c_comment": 35,
    "orders.o_orderkey": 36,
    "orders.o_custkey": 37,
    "orders.o_orderstatus": 38,
    "orders.o_totalprice": 39,
    "orders.o_orderdate": 40,
    "orders.o_orderpriority": 41,
    "orders.o_clerk": 42,
    "orders.o_shippriority": 43,
    "orders.o_comment": 44,
    "lineitem.l_orderkey": 45,
    "lineitem.l_partkey": 46,
    "lineitem.l_suppkey": 47,
    "lineitem.l_linenumber": 48,
    "lineitem.l_quantity": 49,
    "lineitem.l_extendedprice": 50,
    "lineitem.l_discount": 51,
    "lineitem.l_tax": 52,
    "lineitem.l_returnflag": 53,
    "lineitem.l_linestatus": 54,
    "lineitem.l_shipdate": 55,
    "lineitem.l_commitdate": 56,
    "lineitem.l_receiptdate": 57,
    "lineitem.l_shipinstruct": 58,
    "lineitem.l_shipmode": 59,
    "lineitem.l_comment": 60
}
